### ISSUE TITLE
Cant use Kali Linux

### ISSUE THREAD

**Issue by lucahennemann** [kasmtech/workspaces-issues#114]
```
host: proxy
ingest_date: 202201211642
application: kasm_agent
levelname: ERROR
message: Failed to pull image (kasmweb/core-kali-rolling:1.10.0) : 404 Client Error for http+docker://localhost/v1.41/images/kasmweb/core-kali-rolling:1.10.0/json: Not Found ("no such image: kasmweb/core-kali-rolling:1.10.0: No such image: kasmweb/core-kali-rolling:1.10.0")
traceback:
Traceback (most recent call last):
File "docker/api/client.py", line 268, in _raise_for_status
File "requests/models.py", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/kasmweb/core-kali-rolling:1.10.0/json``

**Comment by j-travis** [comment]
Can you please post the output of the following commands

```
df
uname -a
cat /etc/os-relase
```

**Comment by lucahennemann** [comment]
```
root@vps-zap838740-1:~# df
s-relaseFilesystem     1K-blocks     Used Available Use% Mounted on
/dev/rbd66      25671908 20851600   3493204  86% /
none                 492        4       488   1% /dev
tmpfs          198064260        0 198064260   0% /dev/shm
tmpfs          198064260      464 198063796   1% /run
tmpfs               5120        0      5120   0% /run/lock
tmpfs          198064260        0 198064260   0% /sys/fs/cgroup
overlay         25671908 20851600   3493204  86% /var/lib/docker/overlay2/30f280130f598043cb8062faf6053aea4733339c953c92a893f10dbe9aa83cf2/merged
overlay         25671908 20851600   3493204  86% /var/lib/docker/overlay2/879693c19749db722ccbfe050a00127486dc7a4b369cc11ca32be4dbd977bf9c/merged
overlay         25671908 20851600   3493204  86% /var/lib/docker/overlay2/c3ac3c613209775a3a2d6d63fecfb644b6698ae06853bfcaeb7df031ab7abc69/merged
overlay         25671908 20851600   3493204  86% /var/lib/docker/overlay2/48d0fb4449bf26680a2f972f9ee18db177d109385ac517e4f91ce85db188ccb2/merged
overlay         25671908 20851600   3493204  86% /var/lib/docker/overlay2/f7b989760a93ad144c42eedd80000ef3f78a0d451900a46ca18bd7af477f3593/merged
tmpfs           39612852        0  39612852   0% /run/user/0


root@vps-zap838740-1:~# uname -a
Linux vps-zap838740-1 5.4.143-1-pve #1 SMP PVE 5.4.143-1 (Tue, 28 Sep 2021 09:10:37 +0200) x86_64 x86_64 x86_64 GNU/Linux

root@vps-zap838740-1:~# cat /etc/os-relase
cat: /etc/os-relase: No such file or directory
```

**Comment by j-travis** [comment]
@screamz2k , you don't have enough drive space.

The Kali image is very large which is one of the reasons we don't enable it by default. 

The system is trying to pull the image and ultimately failing. The error in the log message that is being reported back from the docker api is slightly misleading, but that is what is happening.

You should be able to see something similar if you try to pull the image manually

```
sudo docker pull kasmweb/core-kali-rolling:1.10.0
```

The install guide recommends 50GB minimum of free hard drive space.
https://kasmweb.com/docs/latest/install/system_requirements.html#resource-requirements

**Comment by j-travis** [comment]
In a separate terminal if you watch your drive space during the pull, you'll see it grow up to 100%, then when the pull fails docker will release back the drive space

```
watch df
```

**Comment by lucahennemann** [comment]
Ok thanks for the help. I didnt think about that, because the log showed a 404 :)
