### ISSUE TITLE
Multiple Servers wont work

### ISSUE THREAD

**Issue by ManuelW77** [kasmtech/workspaces-issues#166]
Hey there,
i have a full working kasm on Server 1.
I set a second server by this documentation: https://www.kasmweb.com/docs/latest/install/multi_server_install.html#install-agent-server-role-s
Agents and Proxy are running on Server 2 and sending heartbeats to Server 1, Server 1 is recognizing the heartbeats and shows me the second agent in kasm admin.

But, if i start some images until i get the message "no more sessions possible", no session is startet on server 2.
i thought installing the agent on multiple servers and register them to Server 1, all agents will create sessions like load balancing?

**Comment by j-travis** [comment]
Yes, thats the way it's supposed to work.

Can you verify that you have enabled the Agent in the UI once it has checked in. When they check in they will show up but are not enabled. You must manually enabled them.

If its already enabled, can you review the logs to see if any errors are reported when trying make a request to that agent. For troubleshooting purposes you could disable the first agent so the system will always try and make sessions on the second.

**Comment by ManuelW77** [comment]
Thank you for fast answering.

The second agent was enabled by me. Now i disabled the first one and try'd again.
Found this in the logs of Server 1

`2022-02-19 19:17:09,280 [DEBUG] __main__.handler: Authenticating Request (/api/v1/hello/)
2022-02-19 19:17:09,281 [WARNING] __main__.handler: Failed to Authenticate Request (/api/v1/hello/)`

but no errors in the logs of Server 2.
If i try manually to go to this path on Server 2 i get "404 not found"

**Comment by j-travis** [comment]
On your main server run the following

```
sudo docker logs -f --tail 10 kasm_api
```

While thats running try and create a session. 

Then go back and look at the tail of the log. They should contain what the issue is. You can post them here if you want.

Its likely that either:
1. Server 1 cant connect to server 2 via the hostname/ip you defined for it
2. Server 2 doen't have enough memory/cpu for the request
3. Server 2 doesn't have the images downloaded (e.g chrome/firefox/centos)

**Comment by ManuelW77** [comment]
Hmm, they get a unauthorized error. The proxy is up and running on server2 with this port 8444.
If i open the URL with the browser i get 405: Method Not Allowed
So server2 is answering.

`2022-02-20 09:10:31,212 [DEBUG] client_api_server: Getting existing available containers                                                                                                                           
2022-02-20 09:10:31,213 [DEBUG] client_api_server: Getting available slots for image: (kasmweb/firefox:1.10.0)                                                                                                     
2022-02-20 09:10:31,229 [DEBUG] client_api_server: Processing Server: (66d64d95-841d-4153-a15c-251f0977144a)                                                                                                       
2022-02-20 09:10:31,232 [DEBUG] client_api_server: Server (66d64d95-841d-4153-a15c-251f0977144a) can support this container. Adding slot                                                                           
2022-02-20 09:10:31,233 [DEBUG] client_api_server: Server (66d64d95-841d-4153-a15c-251f0977144a) can support this container. Adding slot                                                                           
2022-02-20 09:10:31,234 [DEBUG] client_api_server: Server (66d64d95-841d-4153-a15c-251f0977144a) can support this container. Adding slot                                                                           
2022-02-20 09:10:31,236 [DEBUG] client_api_server: Server (66d64d95-841d-4153-a15c-251f0977144a) can support this container. Adding slot                                                                           
2022-02-20 09:10:31,237 [DEBUG] client_api_server: No more slots available for server : (66d64d95-841d-4153-a15c-251f0977144a)                                                                                     
2022-02-20 09:10:31,239 [DEBUG] client_api_server: Prioritized slots (['192.168.1.4', '192.168.1.4', '192.168.1.4', '192.168.1.4'])                                                                                
2022-02-20 09:10:31,240 [DEBUG] client_api_server: Server limited prioritized slots (['192.168.1.4'])                                                                                                              
2022-02-20 09:10:31,247 [DEBUG] client_api_server: Requesting Hello for Server(66d64d95-841d-4153-a15c-251f0977144a) via URL: (https://192.168.1.4:8444/agent/api/v1/hello/)                                       
2022-02-20 09:10:31,270 [DEBUG] client_api_server: Error during Hello request for Server(66d64d95-841d-4153-a15c-251f0977144a) : (Traceback (most recent call last):                                               
  File "provider_manager.py", line 987, in is_host_alive                                                                                                                                                           
  File "urllib/request.py", line 223, in urlopen                                                                                                                                                                   
  File "urllib/request.py", line 532, in open                                                                                                                                                                      
  File "urllib/request.py", line 642, in http_response                                                                                                                                                             
  File "urllib/request.py", line 570, in error                                                                                                                                                                     
  File "urllib/request.py", line 504, in _call_chain                                                                                                                                                               
  File "urllib/request.py", line 650, in http_error_default                                                                                                                                                        
urllib.error.HTTPError: HTTP Error 401: Unauthorized                                                                                                                                                               
)                                                                                                                                                                                                                  
2022-02-20 09:10:31,272 [WARNING] client_api_server: Server(66d64d95-841d-4153-a15c-251f0977144a) is not alive : HTTP Error 401: Unauthorized                                                                      
2022-02-20 09:10:31,273 [ERROR] client_api_server: No resources are available to create the requested Kasm. Please try again later or contact an Administrator : No Agent slots available. No Agent can be contacte
d with enough available resources to provision the image                                                                                                                                                           `

**Comment by j-travis** [comment]
It looks like server 2 was registered with this address `192.168.1.4` . Can you confirm this is not accidently the IP of Server 1.
If you run the following command on Server 1 and Server 2 and repeat the test, can you confirm you get a `Failed to Authenticate Request` message on Server 2 and NOT Server 1

```
sudo docker logs -f --tail 10 kasm_agent
```

When each agent checks in , it will send a unique token that us used to authenticate subsequent requests . Its unique per agent and changes every time the service is restarted. So if the addresses are mixed up , the system wont be able to properly authenticate with the Agent

**Comment by ManuelW77** [comment]
Nope, it is correct. Server1 (main server) is 192.168.1.5 and server2 192.168.1.4
The error log above is from server1, the mainserver with ip 192.168.1.5 while trying to connect to server2

**Comment by j-travis** [comment]
Ok. Please conduct the last test requested and let me know what you see.

Also, can you run the following on server 2 and provide the output

```
sudo docker ps | grep kasm
```

**Comment by ManuelW77** [comment]
log from server1
`2022-02-20 16:47:09,094 [DEBUG] __main__.handler: Authenticating Request (/api/v1/hello/)                                                                                                                          
2022-02-20 16:47:09,096 [WARNING] __main__.handler: Failed to Authenticate Request (/api/v1/hello/)                                                                                                                
2022-02-20 16:47:09,098 [WARNING] tornado.access: 401 POST /api/v1/hello/ (172.24.0.6) 3.93ms                                                                                                                      
2022-02-20 16:47:24,425 [DEBUG] __main__.handler: Sending Heartbeat                                                                                                                                                
2022-02-20 16:47:24,426 [DEBUG] __main__.handler: Current list or prioritized managers (['proxy', 'zeus']                                                                                                          
2022-02-20 16:47:24,427 [INFO] __main__.handler: Sending heartbeat to [https://proxy:443/manager_api/api/v1/heartbeat](https://proxy/manager_api/api/v1/heartbeat)                                                                                               
2022-02-20 16:47:24,438 [DEBUG] __main__.handler: Sending manager request ([https://proxy:443/manager_api/api/v1/heartbeat](https://proxy/manager_api/api/v1/heartbeat))`

log from server2
`2022-02-20 16:47:48,895 [DEBUG] __main__.handler: Sending Heartbeat                                                                                                                                                
2022-02-20 16:47:48,898 [DEBUG] __main__.handler: Current list or prioritized managers (['192.168.1.5', 'zeus']                                                                                                    
2022-02-20 16:47:48,899 [INFO] __main__.handler: Sending heartbeat to https://192.168.1.5:8444/manager_api/api/v1/heartbeat                                                                                        
2022-02-20 16:47:48,910 [DEBUG] __main__.handler: Sending manager request (https://192.168.1.5:8444/manager_api/api/v1/heartbeat)                                                                                  
2022-02-20 16:47:58,186 [DEBUG] __main__.handler: Writing Config                                                                                                                                                   `

ps from server1
`31ce173815ec   kasmweb/nginx:latest              "/docker-entrypoint.…"   6 days ago     Up 2 days             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                                                       
                                                          kasm_proxy
eb4f6ec15ade   kasmweb/share:1.10.0              "/bin/sh -c '/usr/bi…"   6 days ago     Up 2 days             8182/tcp                                                                                            
                                                          kasm_share
5c8637e292f4   kasmweb/agent:1.10.0              "/bin/sh -c '/usr/bi…"   6 days ago     Up 2 days             4444/tcp                                                                                            
                                                          kasm_agent
dab226321b1c   redis:5-alpine                    "docker-entrypoint.s…"   6 days ago     Up 2 days             6379/tcp                                                                                            
                                                          kasm_redis
4d2b18943a89   kasmweb/manager:1.10.0            "/bin/sh -c '/usr/bi…"   6 days ago     Up 2 days             8181/tcp                                                                                            
                                                          kasm_manager
dad3bddd9df3   kasmweb/api:1.10.0                "/bin/sh -c '/usr/bi…"   6 days ago     Up 2 days (healthy)   8080/tcp                                                                                            
                                                          kasm_api
eca3f2e132c3   postgres:12-alpine                "docker-entrypoint.s…"   6 days ago     Up 2 days             5432/tcp                                                                                            
                                                          kasm_db`

ps from server2
`dfda1f2213ba   kasmweb/nginx:latest               "/docker-entrypoint.…"   2 days ago     Up 2 days              80/tcp, 0.0.0.0:8444->8444/tcp, :::8444->8444/tcp                                                 
                                                                                                                                                                            kasm_proxy
c12dd5d30e6e   kasmweb/agent:1.10.0               "/bin/sh -c '/usr/bi…"   2 days ago     Up 2 days              4444/tcp                                                                                          
                                                                                                                                                                            kasm_agent`

**Comment by ManuelW77** [comment]
I solved this problem with a blank new install on booth machines, but get a new problem. i'll open a new issue.
