### ISSUE TITLE
Unable to Create Kali Linux Core Rolling Image

### ISSUE THREAD

**Issue by JY0850** [kasmtech/workspaces-issues#173]
I tried editing the image of Kali Linux to 'kasmweb/core-kali-rolling:1.10.0-rolling', however I kept on getting errors saying that it can't be found. I tried looking everywhere for instructions specifically on how to install rolling images in the Kasm documentation and on other issue posts, however I was not able to get a clear solution to my problem.

**Log:**
host: proxy
ingest_date: 202202271304
application: kasm_agent
levelname: ERROR
message: Failed to pull image (kasmweb/core-kali-rolling:1.10.0-rolling) : 404 Client Error for http+docker://localhost/v1.41/images/kasmweb/core-kali-rolling:1.10.0-rolling/json: Not Found ("no such image: kasmweb/core-kali-rolling:1.10.0-rolling: No such image: kasmweb/core-kali-rolling:1.10.0-rolling")
traceback:
Traceback (most recent call last):
File "docker/api/client.py", line 268, in _raise_for_status
File "requests/models.py", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/kasmweb/core-kali-rolling:1.10.0-rolling/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "ProvisionAgent/provision.py", line 735, in get_image
File "docker/models/images.py", line 456, in pull
File "docker/models/images.py", line 316, in get
File "docker/utils/decorators.py", line 19, in wrapped
File "docker/api/image.py", line 254, in inspect_image
File "docker/api/client.py", line 274, in _result
File "docker/api/client.py", line 270, in _raise_for_status
File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/images/kasmweb/core-kali-rolling:1.10.0-rolling/json: Not Found ("no such image: kasmweb/core-kali-rolling:1.10.0-rolling: No such image: kasmweb/core-kali-rolling:1.10.0-rolling")
process: __main__.handler

**Comment by j-travis** [comment]
Hi,
You likely don't have enough free disk space to pull the image. Please see this related ticket:
https://github.com/kasmtech/workspaces-issues/issues/114

**Comment by j-travis** [comment]
Closing due to lack or response
