### ISSUE TITLE
Unable to connect Agent after setting up Direct To Agent

### ISSUE THREAD

**Issue by jingerpie** [kasmtech/workspaces-issues#195]
I have followed step-by-step in the documentation: https://kasmweb.com/docs/latest/how_to/direct_to_agent.html?highlight=direct

I am starting this instructions from a working multi-server install, with all port at default 443. Both app-1.kasm.example.com and agent-1.kasm.example.com have valid certificates.

After checking Log on Web App Role `sudo docker logs -f kasm_api`, here is what I found:

```
2022-04-26 18:04:19,035 [DEBUG] client_api_server: Successfully authenticated request (request_kasm) for user (admin@kasm.local) at (2603:7000:8200:38f0:a46c:6fc3:7b5f:195e, 162.158.79.5)
2022-04-26 18:04:19,049 [DEBUG] client_api_server: License Check: Current Kasms (0) , License Limit (5) , Remaining (5)
2022-04-26 18:04:19,076 [DEBUG] client_api_server: Using group-level keepalive_expiration of (3600)
2022-04-26 18:04:19,077 [INFO] client_api_server: No existing containers with image (Ubuntu Bionic) exist to assign user (admin@kasm.local)
2022-04-26 18:04:19,078 [DEBUG] client_api_server: Getting existing available containers 
2022-04-26 18:04:19,079 [DEBUG] client_api_server: Getting available slots for image: (kasmweb/ubuntu-bionic-desktop:1.10.0)
2022-04-26 18:04:19,087 [DEBUG] client_api_server: Processing Server: (7837c51e-9747-4d5c-8ff7-fdb31caf7a65)
2022-04-26 18:04:19,089 [DEBUG] client_api_server: Server (7837c51e-9747-4d5c-8ff7-fdb31caf7a65) can support this container. Adding slot
2022-04-26 18:04:19,089 [DEBUG] client_api_server: Server (7837c51e-9747-4d5c-8ff7-fdb31caf7a65) can support this container. Adding slot
2022-04-26 18:04:19,090 [DEBUG] client_api_server: No more slots available for server : (7837c51e-9747-4d5c-8ff7-fdb31caf7a65)
2022-04-26 18:04:19,092 [DEBUG] client_api_server: Prioritized slots (['agent-1.kasm.example.com', 'agent-1.kasm.example.com'])
2022-04-26 18:04:19,092 [DEBUG] client_api_server: Server limited prioritized slots (['agent-1.kasm.example.com'])
2022-04-26 18:04:19,098 [DEBUG] client_api_server: Requesting Hello for Server(7837c51e-9747-4d5c-8ff7-fdb31caf7a65) via URL: (https://agent-1.kasm.example.com:443/agent/api/v1/hello/)
2022-04-26 18:04:19,120 [DEBUG] client_api_server: Successfully authenticated request (new_session_token) for user (admin@kasm.local) at (2603:7000:8200:38f0:a46c:6fc3:7b5f:195e, 162.158.79.100)
2022-04-26 18:04:19,141 [INFO] cherrypy.access.281473383075736: 172.18.0.7 - - [26/Apr/2022:18:04:19] "POST /api/new_session_token/ HTTP/1.1" 200 118 "https://kasm.example.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0"
2022-04-26 18:04:19,195 [DEBUG] client_api_server: Error during Hello request for Server(7837c51e-9747-4d5c-8ff7-fdb31caf7a65) : (Traceback (most recent call last):
  File "provider_manager.py", line 987, in is_host_alive
  File "urllib/request.py", line 223, in urlopen
  File "urllib/request.py", line 532, in open
  File "urllib/request.py", line 642, in http_response
  File "urllib/request.py", line 570, in error
  File "urllib/request.py", line 504, in _call_chain
  File "urllib/request.py", line 650, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
)
2022-04-26 18:04:19,195 [WARNING] client_api_server: Server(7837c51e-9747-4d5c-8ff7-fdb31caf7a65) is not alive : HTTP Error 403: Forbidden
2022-04-26 18:04:19,197 [ERROR] client_api_server: No resources are available to create the requested Kasm. Please try again later or contact an Administrator : No Agent slots available. No Agent can be contacted with enough available resources to provision the image
2022-04-26 18:04:19,199 [INFO] cherrypy.access.281473383075736: 172.18.0.7 - - [26/Apr/2022:18:04:19] "POST /api/request_kasm/ HTTP/1.1" 200 254 "https://app-1.kasm.example.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0"
```

**Comment by j-travis** [comment]
Here are some thing to try:

1. Tail the logs on the agent server. See if the hello request is making it there and if its being denied

```
sudo docker logs -f kasm_agent
```

2. If its not making it there , try and Identify if there is any firewall/waf in between the Kasm webapp server and the agent. WAFs may block the request because the user agent will be from python/urllib  - so it will look like a bot/script . In that case you'll need to make an exclusion in your WAF.

**Comment by jingerpie** [comment]
Thank you Travis for your fast response! After trying out your suggestion, and here are what I discover, please have a look~


## Test 1: Creating a session on Web App Sever:
```
# Web App Sever
Requesting Hello for Server(7837c51e-9747-4d5c-8ff7-fdb31caf7a65) via URL: (https://agent-1.kasm.example.com:443/agent/api/v1/hello/)
```
**Agent Log does not have any new record, meaning it is not receiving hello request from Web App Sever**

---

## Test 2: Sending hello request manually on Web App Sever:
```
sudo docker exec -it kasm_proxy wget https://agent-1.kasm.example.com:443/agent/api/v1/hello/
```
```
# Web App Sever
Connecting to agent-1.kasm.example.com:443 (XXX.XXX.XX.XXX:443)
wget: server returned error: HTTP/1.1 405 Method Not Allowed

# Agent Sever
2022-04-26 19:04:37,435 [WARNING] tornado.access: 405 GET /api/v1/hello/ (172.18.0.3) 0.75ms
```
**Agent is able to receive hello request from Web App Sever, meaning there are no WAFs blocking the request**

**Comment by jingerpie** [comment]
After double checking WAF on Cloudflare, I discover that Python-urllib/3.6 is indeed block by WAF
![IMG_0002](https://user-images.githubusercontent.com/72108315/165376884-4a02ab23-6296-49be-8206-cf815ce0456d.jpg)

**Comment by jingerpie** [comment]
I was able to solve this issue by setting up a firewall rule on Cloudflare to bypass Browser Integrity Check. Below is how I do it. Hopefully this can help anyone out there experiencing similar issue as me.
![IMG_0003](https://user-images.githubusercontent.com/72108315/165377696-9280cc53-701c-4dcb-9c40-97fdf4717804.jpg)

**Comment by j-travis** [comment]
Excellent @JingerTea , thanks for leaving the detailed feedback and testing steps.
