### ISSUE TITLE
Support network_mode for additional images

### ISSUE THREAD

**Issue by Ian-Kasmweb** [kasmtech/workspaces-issues#21]
**[Original report](https://bitbucket.org/kasmtech/kasm_release/issue/21) by jiggyjigsj (Bitbucket: [jiggyjigsj](https://bitbucket.org/jiggyjigsj), GitHub: [jiggyjigsj](https://github.com/jiggyjigsj)).**

----------------------------------------

I was trying to share another container’s network with provision images and i ran into the following error while attempting to configure the network in the json.

‌

The config should be support by docker api: [https://docker-py.readthedocs.io/en/stable/containers.html](https://docker-py.readthedocs.io/en/stable/containers.html)

**Docker Run Config Override \(JSON\)**

```
{
  "network_mode":"container:CONTAINER_NAME",
  "hostname":"kasm-test"
}
```

‌

```
host: kasm_proxy
levelname: ERROR
ingest_date: 202011130527
application: kasm_agent
process: __main__.handler
traceback:
Traceback (most recent call last):
File "/opt/atlassian/pipelines/agent/build/provision_agent/ProvisionAgent/__init__.py", line 241, in post
File "/opt/atlassian/pipelines/agent/build/provision_agent/ProvisionAgent/provision.py", line 376, in provision
File "/opt/atlassian/pipelines/agent/build/build/virtual_environment/lib/python3.5/site-packages/docker-2.7.0-py3.5.egg/docker/models/containers.py", line 713, in run
RuntimeError: The options "network" and "network_mode" can not be used together.
message: Exception creating Kasm: Traceback (most recent call last): File "/opt/atlassian/pipelines/agent/build/provision_agent/ProvisionAgent/__init__.py", line 241, in post File "/opt/atlassian/pipelines/agent/build/provision_agent/ProvisionAgent/provision.py", line 376, in provision File "/opt/atlassian/pipelines/agent/build/build/virtual_environment/lib/python3.5/site-packages/docker-2.7.0-py3.5.egg/docker/models/containers.py", line 713, in run RuntimeError: 
The options "network" and "network_mode" can not be used together.
```

‌

**Comment by teja-kasm** [comment]
We’re currently enhancing our GitHub issue tracker to improve organization and efficiency.

As part of this process, we’re closing older issues to help keep the tracker focused on current and active topics.

If this issue is still relevant or you’re still experiencing the problem, please feel free to create a new issue.

Thank you for your understanding!
