### ISSUE TITLE
Using another container as network?

### ISSUE THREAD

**Issue by imightbelosthere** [kasmtech/workspaces-issues#240]
Hi,

I'm testing KASM and I've deployed a gluetun on the KASM server (docker container of course) and was wondering if there's any way, either by adding something on the docker exec config override or something, to use that container as the network for the image I want to use?

Usually on a docker compose I would place something like network_mode: "service:gluetun" or network_mode: "container:gluetun" if it is not in the same docker compose file, but I can't figure out how I would be able to use this / integrate this with KASM.

I know there's the VPN Sidecar and read the documentation and it "sort of works". The added benefit in this scenario is that if the container's not up or "dies" somehow, the connection ceases to exist, which is ideal for my scenario.

Thanks for all and any inputs!

**Comment by imightbelosthere** [comment]
Bumping this one up before a bot comes and says "it's all good" and closes it :)

**Comment by mmcclaskey** [comment]
As of today, the doc you mentioned at https://kasmweb.com/docs/latest/how_to/vpn_sidecar.html, is the way to handle this scenario within Kasm. 

We do have in our backlog a feature called 'Kasm Stacks', which would essentially let you launch a Kasm session that consists of more than one container and allow for custom docker networking between them. We do not have a timeline for that yet, but internally it is highly desired feature of our dev team.

**Comment by imightbelosthere** [comment]
Hi Matt,

Thanks for replying and for the additional information. Meanwhile, is there a way to override the network mode or configure it somehow through the exec config override?

There's a run option that allows us to configure the container at start, but to be honest I don't know how I should translate that into the JSON format of the exec config override, if there even is such an option.

Thanks once again for your help and inputs.

________________________________

**Comment by j-travis** [comment]
@imightbelosthere ,

Sorry, network_mode doesnt work in the kasm ecosystem.  We've tried the last time it was asked: https://github.com/kasmtech/workspaces-issues/issues/21#issuecomment-973134255

The reason has to do with how traffic is routed / proxied to the session container.  

Using network_mode to link containers is also limiting in that the only one container can bind to a given port at a time. Being that kasm sessions bind to several ports it would mean only one could be linked to the vpn container at a given time.

**Comment by sts64** [comment]
@mmcclaskey 

I've been trying for some time to achieve this using the vpn sidecar method you mention but when launching an image connected to 'vpn-1' I get the unexpected error message.

Is there any common errors or troubleshooting methods you are aware of?

Thanks

**Comment by mmcclaskey** [comment]
@sts64 , sorry, I have not implemented a vpn sidecar solution myself so I am not aware of that error.

**Comment by sts64** [comment]
@j-travis have you successfully implemented a VPN sidecar for Kasm?

**Comment by j-travis** [comment]
Yes, 
Originally posted about here
 - https://www.reddit.com/r/kasmweb/comments/t2awm4/kasm_tailscale_vpn_sidecar_example_help_wanted/

And then added to the docs already mentioned
-  https://kasmweb.com/docs/latest/how_to/vpn_sidecar.html


If you are getting an error, post the logs with the details of the error in order to troubleshoot.

You can look for Error messages in the Logging page within the UI.

You can also run a tail of the container logs 
 - `sudo docker logs -f --tail 100 kasm_api`
 - `sudo docker logs -f --tail 100 kasm_agent`

Then repeat the test to capture the logs, and look for errors / post them here

**Comment by sts64** [comment]
Thanks @j-travis 

Kasm_agent logs:

2022-10-20 15:00:18,860 [DEBUG] client_api_server: Successfully authenticated request (wrapper_function) for user (sc) at (xx.xx.xx.xx)
2022-10-20 15:00:18,866 [DEBUG] client_api_server: License Check: Current Kasms (0) , License Limit (5) , Remaining (5)
2022-10-20 15:00:18,899 [DEBUG] client_api_server: Using exec_config {'user': 'root', 'privileged': True, 'cmd': "bash -c 'ip route delete default && ip route add default via 172.20.0.2'", 'environment': {'KASM_URL': ''}}
2022-10-20 15:00:18,909 [DEBUG] client_api_server: Using group-level keepalive_expiration of (3600)
2022-10-20 15:00:18,909 [INFO] client_api_server: No existing containers with image (CentOS 7) exist to assign user (sc)
2022-10-20 15:00:18,910 [DEBUG] client_api_server: Function (provider_manager.assign_container) executed in (0.0059566497802734375) seconds
2022-10-20 15:00:18,911 [DEBUG] client_api_server: Getting existing available containers 
2022-10-20 15:00:18,912 [DEBUG] client_api_server: Getting available slots for image: (kasmweb/centos-7-desktop:1.11.0)
2022-10-20 15:00:18,918 [DEBUG] client_api_server: Processing Server: (5a41730a-acb5-4681-ac90-be088e234fa8)
2022-10-20 15:00:18,919 [DEBUG] client_api_server: Server (5a41730a-acb5-4681-ac90-be088e234fa8) has one of the requested restricted image networks (['vpn-1'])
2022-10-20 15:00:18,920 [DEBUG] client_api_server: Server (5a41730a-acb5-4681-ac90-be088e234fa8) can support this container. Adding slot
2022-10-20 15:00:18,921 [DEBUG] client_api_server: Server (5a41730a-acb5-4681-ac90-be088e234fa8) can support this container. Adding slot
2022-10-20 15:00:18,922 [DEBUG] client_api_server: Server (5a41730a-acb5-4681-ac90-be088e234fa8) can support this container. Adding slot
2022-10-20 15:00:18,922 [DEBUG] client_api_server: Server (5a41730a-acb5-4681-ac90-be088e234fa8) can support this container. Adding slot
2022-10-20 15:00:18,923 [DEBUG] client_api_server: Server (5a41730a-acb5-4681-ac90-be088e234fa8) can support this container. Adding slot
2022-10-20 15:00:18,924 [DEBUG] client_api_server: Server 5a41730a-acb5-4681-ac90-be088e234fa8 does not have required memory remaining (2325586432 remaining)
2022-10-20 15:00:18,925 [DEBUG] client_api_server: No more slots available for server : (5a41730a-acb5-4681-ac90-be088e234fa8)
2022-10-20 15:00:18,925 [DEBUG] client_api_server: Function (provider_manager.get_available_slots) executed in (0.01245427131652832) seconds
2022-10-20 15:00:18,927 [DEBUG] client_api_server: Prioritized slots (['proxy', 'proxy', 'proxy', 'proxy', 'proxy'])
2022-10-20 15:00:18,927 [DEBUG] client_api_server: Server limited prioritized slots (['proxy'])
2022-10-20 15:00:18,928 [DEBUG] client_api_server: Function (provider_manager.prioritize_slots) executed in (0.001837015151977539) seconds
2022-10-20 15:00:18,932 [DEBUG] client_api_server: Requesting Hello for Server(5a41730a-acb5-4681-ac90-be088e234fa8) via URL: (https://proxy:8443/agent/api/v1/hello/)
2022-10-20 15:00:18,938 [DEBUG] client_api_server: Server(5a41730a-acb5-4681-ac90-be088e234fa8) is alive
2022-10-20 15:00:18,938 [DEBUG] client_api_server: Function (provider_manager.is_host_alive) executed in (0.00653076171875) seconds
2022-10-20 15:00:18,939 [DEBUG] client_api_server: Found existing server capacity: (<data.model.Server object at 0x7f3685b77820>).
2022-10-20 15:00:18,941 [DEBUG] client_api_server: Server (5a41730a-acb5-4681-ac90-be088e234fa8) has the requested image (kasmweb/centos-7-desktop:1.11.0) 
2022-10-20 15:00:18,943 [DEBUG] client_api_server: Requesting Hello for Server(5a41730a-acb5-4681-ac90-be088e234fa8) via URL: (https://proxy:8443/agent/api/v1/hello/)
2022-10-20 15:00:18,949 [DEBUG] client_api_server: Server(5a41730a-acb5-4681-ac90-be088e234fa8) is alive
2022-10-20 15:00:18,951 [DEBUG] client_api_server: Function (provider_manager.is_host_alive) executed in (0.007323741912841797) seconds
2022-10-20 15:00:18,951 [INFO] client_api_server: Creating Kasm on Server: (5a41730a-acb5-4681-ac90-be088e234fa8)
2022-10-20 15:00:18,952 [DEBUG] client_api_server: Requesting Kasm via URL: (https://proxy:8443/agent/api/v1/create_container/)
2022-10-20 15:00:19,632 [ERROR] client_api_server: Error during Create request for Server(5a41730a-acb5-4681-ac90-be088e234fa8) : (Exception creating Kasm: Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/exec/75678eb65fe82eb53efba8fe77f51163846431580c8d028af5723f4201e5d18e/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__init__.py", line 501, in post
  File "provision.py", line 1019, in container_exec
  File "docker/models/containers.py", line 198, in exec_run
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/exec_api.py", line 166, in exec_start
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/exec/75678eb65fe82eb53efba8fe77f51163846431580c8d028af5723f4201e5d18e/start: Internal Server Error ("OCI runtime exec failed: exec failed: unable to start container process: unable to apply caps: operation not permitted: unknown")
)
2022-10-20 15:00:19,633 [DEBUG] client_api_server: Function (provider_manager.create_kasm_from_slot) executed in (0.6920831203460693) seconds
2022-10-20 15:00:19,634 [DEBUG] client_api_server: Function (provider_manager.get_container) executed in (0.7225360870361328) seconds
2022-10-20 15:00:19,635 [ERROR] client_api_server: An Unexpected Error occurred creating the Kasm. Please contact an Administrator : Error during Create request for Server(5a41730a-acb5-4681-ac90-be088e234fa8) : (Exception creating Kasm: Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/exec/75678eb65fe82eb53efba8fe77f51163846431580c8d028af5723f4201e5d18e/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__init__.py", line 501, in post
  File "provision.py", line 1019, in container_exec
  File "docker/models/containers.py", line 198, in exec_run
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/exec_api.py", line 166, in exec_start
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/exec/75678eb65fe82eb53efba8fe77f51163846431580c8d028af5723f4201e5d18e/start: Internal Server Error ("OCI runtime exec failed: exec failed: unable to start container process: unable to apply caps: operation not permitted: unknown")
)
2022-10-20 15:00:19,636 [DEBUG] client_api_server: Function (client_api.request_kasm) executed in (0.7753133773803711) seconds
2022-10-20 15:00:19,638 [INFO] cherrypy.access.139872725451104: 172.18.0.8 - - [20/Oct/2022:15:00:19] "POST /api/request_kasm/ HTTP/1.1" 200 1475 "https://xx.xx.xx.xx:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.47"

**Comment by j-travis** [comment]
What is in your Docker Run Config Override

**Comment by sts64** [comment]
{"hostname":"kasm"}

**Comment by j-travis** [comment]
Can you share more about your host machine? Can you past the output of these commands

```
cat /etc/os-release
df
sudo docker info 
uname -a
```

Did you install workspaces inside an LXC?

**Comment by sts64** [comment]
Yes, it is installed in an LX running on Proxmox.

Output:

> PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
> NAME="Debian GNU/Linux"
> VERSION_ID="11"
> VERSION="11 (bullseye)"
> VERSION_CODENAME=bullseye
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"
> Filesystem                       1K-blocks     Used Available Use% Mounted on
> /dev/mapper/pve-vm--100--disk--0 205314024 50484772 144327108  26% /
> none                                   492        4       488   1% /dev
> tmpfs                              8006632        0   8006632   0% /dev/shm
> tmpfs                              3202656      772   3201884   1% /run
> tmpfs                                 5120        0      5120   0% /run/lock
> overlay                          205314024 50484772 144327108  26% /var/lib/docker/overlay2/ba9fbecf41b8bb48b55cef50efa9243c9c08d82b9e5300561c0dc96cb47c1090/merged
> overlay                          205314024 50484772 144327108  26% /var/lib/docker/overlay2/09a6cf860ec0fc70deb09605c12043c55967e09df1bbdfead66082d50ecafe3c/merged
> overlay                          205314024 50484772 144327108  26% /var/lib/docker/overlay2/585466afe88b7c2ee924a836ec1d42ed71c365b636035d0e43449cc70d69715b/merged
> overlay                          205314024 50484772 144327108  26% /var/lib/docker/overlay2/08ba45de83edf36f2632438cbc4b3c89719e5658635b65438e8b21c440a3a0c1/merged
> overlay                          205314024 50484772 144327108  26% /var/lib/docker/overlay2/2aa6b47157b1c32ecd4e686b186ff3718b1412ca78b124282fa7976e7461ea96/merged
> overlay                          205314024 50484772 144327108  26% /var/lib/docker/overlay2/6084e132e1d2bbc06fe98c145beb9a01d7932bcee71ec6623bed5e6f34edc759/merged
> overlay                          205314024 50484772 144327108  26% /var/lib/docker/overlay2/9f5b7016756814cfd0701e4621dbef18bac709bf3c959ea6b1b2b210a66987a4/merged
> overlay                          205314024 50484772 144327108  26% /var/lib/docker/overlay2/8ced219203d51f5a1989825e94c655ea9a4113c3fdc40398c7fabb217a1da833/merged
> Client:
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   app: Docker App (Docker Inc., v0.9.1-beta3)
>   buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
>   compose: Docker Compose (Docker Inc., v2.5.0)
> 
> Server:
>  Containers: 20
>   Running: 8
>   Paused: 0
>   Stopped: 12
>  Images: 40
>  Server Version: 20.10.19
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: true
>   userxattr: false
>  Logging Driver: json-file
>  Cgroup Driver: systemd
>  Cgroup Version: 2
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
>  runc version: v1.1.4-0-g5fd4c4d
>  init version: de40ad0
>  Security Options:
>   seccomp
>    Profile: default
>   cgroupns
>  Kernel Version: 5.15.30-2-pve
>  Operating System: Debian GNU/Linux 11 (bullseye)
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 4
>  Total Memory: 9.766GiB
>  Name: CT100
>  ID: VG7Z:GTSH:LSSG:V3UX:6BXH:VVQA:TIZ3:SK4K:ZAO6:3QDR:KH64:M5LL
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: false
>  Registry: https://index.docker.io/v1/
>  Labels:
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false
> 
> Linux CT100 5.15.30-2-pve #1 SMP PVE 5.15.30-3 (Fri, 22 Apr 2022 18:08:27 +0200) x86_64 GNU/Linux
> 
>

**Comment by j-travis** [comment]
It looks like you are running into a general problem with running docker in LXC. This seems related:

https://serverfault.com/questions/946854/docker-inside-lxc-starting-container-process-caused-apply-caps-operation-not-p

Its worth noting, you will likely continually run into issues like this.   You might consider running in a standard VM while you try to get things working.  Then if you'd like, try to migrate to LXC

**Comment by sts64** [comment]
Thanks @j-travis 

I will give this a go
