### ISSUE TITLE
[Bug] - Issue using proxy after upgrade to 1.12.0

### ISSUE THREAD

**Issue by thegreymatter** [kasmtech/workspaces-issues#318]
### Existing Resources

**Describe the bug**
after upgrading from 1.10.0 to 1.12.0 I'm having troubles connecting my agent through proxy. 

when connecting to the desktop i receive 500 error when accessing the following URL - 

https://[REDACTED].com/desktop/[REDACTED]/vnc/vnc.html?video_quality=2&enable_webp=false&idle_disconnect=false&password=&autoconnect=1&path=desktop/[REDACTED]/vnc/websockify&cursor=true&resize=remote&clipboard_up=true&clipboard_down=true&clipboard_seamless=true&toggle_control_panel=false

--

in the server side logs i'm receiving the following errors - 
Unhandled exception occurred Traceback (most recent call last): File "cherrypy/_cprequest.py", line 628, in respond File "cherrypy/_cprequest.py", line 687, in _do_respond File "cherrypy/lib/encoding.py", line 219, in __call__ File "cherrypy/_cpdispatch.py", line 54, in __call__ File "client_api.py", line 1597, in kasm_connect KeyError: 'connection_type'

**Comment by mmcclaskey** [comment]
@thegreymatter , please try creating a new Workspace (image). Manually copy and paste the values from the old Workspace that is not working, into the new Workspace definition. Ensure that you change the `Docker Image` from a 1.10.0 image to 1.12.0.

**Comment by kodxana** [comment]
I have similar error just in my case it's 502 error. Changing zones not fixes issue.

**Comment by j-travis** [comment]
> I have similar error just in my case it's 502 error. Changing zones not fixes issue.

Where is the 502 coming from? Can you access Kasm directly just not through the proxy?

I also recommend you verify the Kasm containers are running:

`sudo docker ps`

If they are failing or continuously restarting, you can tail the logs to see if something interesting is there:

```
sudo docker logs -f --tail 100 <container>
```

**Comment by teja-kasm** [comment]
We’re currently enhancing our GitHub issue tracker to improve organization and efficiency.

As part of this process, we’re closing older issues to help keep the tracker focused on current and active topics.

If this issue is still relevant or you’re still experiencing the problem, please feel free to create a new issue.

Thank you for your understanding!
