### ISSUE TITLE
kasm_agent&kasm_api(error)

### ISSUE THREAD

**Issue by hassanhashem22** [kasmtech/workspaces-issues#392]
i need any solution for these errors

Create Kasm
An Unexpected Error occurred creating the Kasm. Please contact an Administrator

Exception creating Kasm: Traceback (most recent call last): File "__init__.py", line 538, in post File "provision.py", line 1199, in provision File "provision.py", line 1351, in generate_nginx_config Exception: Nginx failed to reload after generating config for container (ee012629b176626465daa94cd5226c2b2c20844b36d4c650702a6a057a7a6261) Traceback (most recent call last): File "__init__.py", line 538, in post File "provision.py", line 1199, in provision File "provision.py", line 1351, in generate_nginx_config Exception: Nginx failed to reload after generating config for container (ee012629b176626465daa94cd5226c2b2c20844b36d4c650702a6a057a7a6261)

An Unexpected Error occurred creating the Kasm. Please contact an Administrator : Error during Create request for Server(9a5e35cd-aa47-45f5-8070-4b42679323ef) : (Exception creating Kasm: Traceback (most recent call last): File "__init__.py", line 538, in post File "provision.py", line 1199, in provision File "provision.py", line 1351, in generate_nginx_config Exception: Nginx failed to reload after generating config for container (ee012629b176626465daa94cd5226c2b2c20844b36d4c650702a6a057a7a6261) )

Error during Create request for Server(9a5e35cd-aa47-45f5-8070-4b42679323ef) : (Exception creating Kasm: Traceback (most recent call last): File "__init__.py", line 538, in post File "provision.py", line 1199, in provision File "provision.py", line 1351, in generate_nginx_config Exception: Nginx failed to reload after generating config for container (ee012629b176626465daa94cd5226c2b2c20844b36d4c650702a6a057a7a6261) )

Nginx reload failed (2023/05/21 22:43:41 [emerg] 95#95: host not found in upstream "kasm_guac" in /etc/nginx/conf.d/services.d/kasmguac.conf:10 nginx: [emerg] host not found in upstream "kasm_guac" in /etc/nginx/conf.d/services.d/kasmguac.conf:10 )

Nginx failed to reload after generating config for container (ee012629b176626465daa94cd5226c2b2c20844b36d4c650702a6a057a7a6261)

**Comment by j-travis** [comment]
When opening a bug ticket we ask for a number of items that help orient us on your setup. Can you please complete them:
https://github.com/kasmtech/workspaces-issues/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBug%5D+-+Example

The first thing I'd do is try restarting the services

```
sudo /opt/kasm/bin/stop
sudo /opt/kasm/bin/start
```

**Comment by hassanhashem22** [comment]
> When opening a bug ticket we ask for a number of items that help orient us on your setup. Can you please complete them: https://github.com/kasmtech/workspaces-issues/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBug%5D+-+Example
> 
> The first thing I'd do is try restarting the services
> 
> ```
> sudo /opt/kasm/bin/stop
> sudo /opt/kasm/bin/start
> ```

the problems still exist

**Comment by hassanhashem22** [comment]
Now i am getting that error only "No resources are available to create the requested Kasm. Please try again later or contact an Administrator : No Agent slots available. No Agent can be contacted with enough available resources to provision the image"
how to solve it, i am using kasm 1.13.1

**Comment by j-travis** [comment]
Please review the following documentation:
https://kasmweb.com/docs/latest/guide/troubleshooting.html#no-resources-available

**Comment by hassanhashem22** [comment]
> Please review the following documentation: https://kasmweb.com/docs/latest/guide/troubleshooting.html#no-resources-available

i Have already tried this but no change the problem still exist

**Comment by j-travis** [comment]
When opening a bug ticket we ask for a number of items that help orient us on your setup. Can you please complete them and paste them in the ticket:
https://github.com/kasmtech/workspaces-issues/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBug%5D+-+Example

**Comment by hassanhashem22** [comment]
> When opening a bug ticket we ask for a number of items that help orient us on your setup. Can you please complete them and paste them in the ticket: https://github.com/kasmtech/workspaces-issues/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBug%5D+-+Example

i don't know if this is bug or not i am not reporting a bug right now i am just reporting an issue i just want to solve the issue of no resources available

**Comment by teja-kasm** [comment]
We’re currently enhancing our GitHub issue tracker to improve organization and efficiency.

As part of this process, we’re closing older issues to help keep the tracker focused on current and active topics.

If this issue is still relevant or you’re still experiencing the problem, please feel free to create a new issue.

Thank you for your understanding!
