### ISSUE TITLE
[Bug] - Guac is not starting

### ISSUE THREAD

**Issue by jknyght9** [kasmtech/workspaces-issues#426]
**Describe the bug**
Workspaces will not connect to container session. Guac appears not be down.

**To Reproduce**
1. I dont really know how to reproduce this

**Expected behavior**
Expecting guac to start and connect to a container

**Screenshots**

docker logs --tail -f kasm_guac
```
> GClient@1.1.2 start
> NODE_ENV=production node app.js

/gclient/logger.js:61
  errorEventName: config.kasmguac.logging.errorEventName,
                         ^

TypeError: Cannot read properties of undefined (reading 'kasmguac')
    at Object.<anonymous> (/gclient/logger.js:61:26)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/gclient/app.js:12:16)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
```

**Workspaces Version**
Version 1.13

**Workspaces Installation Method**
Single Server

**Comment by teja-kasm** [comment]
We’re currently enhancing our GitHub issue tracker to improve organization and efficiency.

As part of this process, we’re closing older issues to help keep the tracker focused on current and active topics.

If this issue is still relevant or you’re still experiencing the problem, please feel free to create a new issue.

Thank you for your understanding!
