### ISSUE TITLE
[Bug] - Kasm Share, not working as intended

### ISSUE THREAD

**Issue by WinterFe** [kasmtech/workspaces-issues#480]
**Describe the bug**
Using Kasm Share, the chat / live viewers do not work as intended

**To Reproduce**
1. Go to a workspace, share the workspace, invite a friend
2. Click on chat, send a message
3. See error

**Expected behavior**
The message sends in Kasm Share chat box, and the viewer section updates properly.

**Screenshots**
N/A

**Workspaces Version**
1.14.0.32d10f

**Workspaces Installation Method**
Single server

**Client Browser:**
 - OS: Windows 11
 - Browser: Vivaldi
 - Version: 6.4. 3160.41

**Workspace Server Information:**
 - `uname -a`: `Linux vps-1c8ffa4d 6.2.0-34-generic #34-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep  4 13:06:55 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - `cat /etc/os-release`:
 ```
 PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=lunar
LOGO=ubuntu-logo
 ```
 - `sudo docker info`:
 ```
 Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 10
  Running: 10
  Paused: 0
  Stopped: 0
 Images: 21
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-34-generic
 Operating System: Ubuntu 23.04
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.24GiB
 Name: vps-1c8ffa4d
 ID: 4ecbe726-e0d1-437d-9ece-12ea1272938d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 ```
 - `sudo docker ps | grep kasm`:
 ```
 f0f769945774   kasmweb/nginx:1.25.1                               "/docker-entrypoint.…"   About an hour ago   Up 28 minutes             80/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp                                                        kasm_proxy
43c3ef998d7e   kasmweb/agent:1.14.0                               "/bin/sh -c '/usr/bi…"   About an hour ago   Up 28 minutes (healthy)   4444/tcp                                                                                                 kasm_agent
515bd8c90684   kasmweb/share:1.14.0                               "/bin/sh -c '/usr/bi…"   About an hour ago   Up 28 minutes (healthy)   8182/tcp                                                                                                 kasm_share
09f3911be3a4   kasmweb/api:1.14.0                                 "/bin/sh -c '/usr/bi…"   About an hour ago   Up 28 minutes (healthy)   8080/tcp                                                                                                 kasm_api
80f631d46dbf   redis:5-alpine                                     "docker-entrypoint.s…"   About an hour ago   Up 29 minutes             6379/tcp                                                                                                 kasm_redis
2cd6988b64c9   kasmweb/kasm-guac:1.14.0                           "/dockerentrypoint.sh"   About an hour ago   Up 28 minutes (healthy)                                                                                                            kasm_guac
0ba1c338f722   kasmweb/manager:1.14.0                             "/bin/sh -c '/usr/bi…"   About an hour ago   Up 28 minutes (healthy)   8181/tcp                                                                                                 kasm_manager
d72e6b49565a   postgres:12-alpine                                 "docker-entrypoint.s…"   About an hour ago   Up 28 minutes (healthy)   5432/tcp                                                                                                 kasm_db
```

Error stack from logging page:

```
Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f35644d5d30>)
Traceback (most recent call last):
  File "tornado/ioloop.py", line 758, in _run_callback
  File "tornado/stack_context.py", line 300, in null_wrapper
  File "tornado/iostream.py", line 752, in wrapper
  File "tornado/stack_context.py", line 300, in null_wrapper
  File "tornado/websocket.py", line 488, in on_connection_close
  File "share_server.py", line 282, in on_close
  File "share_server.py", line 45, in publish
  File "tornadoredis/client.py", line 1089, in publish
  File "tornado/gen.py", line 239, in wrapper
  File "tornado/concurrent.py", line 658, in future_add_done_callback
  File "tornado/stack_context.py", line 300, in null_wrapper
  File "tornado/gen.py", line 232, in final_callback
  File "tornado/gen.py", line 326, in wrapper
  File "tornadoredis/client.py", line 407, in execute_command
  File "tornadoredis/connection.py", line 74, in connect
  File "tornado/iostream.py", line 1222, in __init__
TypeError: __init__() got an unexpected keyword argument 'io_loop'
```

**Comment by j-travis** [comment]
Thank you for reporting. Confirmed there is a bug here.  
You may be able to work around the issue with the following instructions. Please let us know if it works for you:

Please use the following steps on your Kasm server, (or the WebApp role if using multi-server) in your ecosystem to receive the share server fix.

1. Open a terminal on your WebApp Server

2. Open the docker-compose.yaml file in an editor

```
sudo nano /opt/kasm/current/docker/docker-compose.yaml
```

In the `kasm_share` section, adjust the tag for the share container to `1.14.0-alpine` in the image section and save the file:

```
image: "kasmweb/share:1.14.0-alpine"
```

It should look similar to this:

![image](https://github.com/kasmtech/workspaces-issues/assets/48762190/bc6a59d4-7c1f-4f15-82bd-9cee57f76c1c)

3. Stop the Kasm services

```
sudo /opt/kasm/bin/stop
```

4. Remove the exiting kasm_share container
sudo docker rm -f kasm_share

5. Start the services

```
sudo /opt/kasm/bin/start
```

Log back into Kasm and start a new session, and toggle sharing on. Now hopefully the chat widget will function again

**Comment by teja-kasm** [comment]
We’re currently enhancing our GitHub issue tracker to improve organization and efficiency.

As part of this process, we’re closing older issues to help keep the tracker focused on current and active topics.

If this issue is still relevant or you’re still experiencing the problem, please feel free to create a new issue.

Thank you for your understanding!
