### ISSUE TITLE
Gamepad pass-through in Proxmox LXC environment doesn't work

### ISSUE THREAD

**Issue by evk404** [kasmtech/workspaces-issues#502]
Workspaces fail to create when the Gamepad Pass-through option is enabled and Kasm is running in Proxmox LXC.

1. Install Kasm in Proxmox LXC container (any supported OS)
2. Enable *allow_kasm_gamepad* option
3. Try to create ANY workspace session
4. The workspace fails to create. The pop-up error message appears: "An Unexpected Error occurred creating the Kasm. Please contact an Administrator".
![image](https://github.com/kasmtech/workspaces-issues/assets/129557327/117f1f18-a9d2-4407-b793-f5a05776f8d6)
The log messages:

```
host: KASM
ingest_date: 202401041950
application: kasm_api
levelname: ERROR
kasm_user_name: admin@kasm.local
process: client_api_server
client_ip: 192.168.101.100
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
message
An Unexpected Error occurred creating the Kasm. Please contact an Administrator : Error during Create request for Server(f9836345-9935-41c4-9f30-61d0b7bf52db) : (Exception creating Kasm: Traceback (most recent call last):
  File "__init__.py", line 539, in post
  File "provision.py", line 1494, in provision
Exception: Could not create gamepad devices
)
```

```
host: KASM
ingest_date: 202401041950
application: kasm_api
levelname: ERROR
kasm_user_name: admin@kasm.local
process: client_api_server
client_ip: 192.168.101.100
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
message
Error during Create request for Server(f9836345-9935-41c4-9f30-61d0b7bf52db) : (Exception creating Kasm: Traceback (most recent call last):
  File "__init__.py", line 539, in post
  File "provision.py", line 1494, in provision
Exception: Could not create gamepad devices
)
```

```
host: proxy
ingest_date: 202401041950
application: kasm_agent
levelname: ERROR
process: __main__.handler
message
Exception creating Kasm: Traceback (most recent call last):
  File "__init__.py", line 539, in post
  File "provision.py", line 1494, in provision
Exception: Could not create gamepad devices
Traceback (most recent call last):
  File "__init__.py", line 539, in post
  File "provision.py", line 1494, in provision
Exception: Could not create gamepad devices
```

```
host: proxy
ingest_date: 202401041950
application: kasm_agent
levelname: ERROR
process: __main__.handler
message
Gamepad Helper Logs: Traceback (most recent call last):
  File "evdev/uinput.py", line 261, in _verify
FileNotFoundError: [Errno 2] No such file or directory: '/dev/uinput'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "__init__.py", line 274, in <module>
  File "__init__.py", line 209, in create_devices
  File "__init__.py", line 215, in create_device
  File "evdev/uinput.py", line 124, in __init__
  File "evdev/uinput.py", line 267, in _verify
evdev.uinput.UInputError: "/dev/uinput" does not exist or is not a character device file - verify that the uinput module is loaded
[7] Failed to execute script '__init__' due to unhandled exception!
```

```
host: proxy
ingest_date: 202401041950
application: kasm_agent
levelname: ERROR
process: __main__.handler
message
Timeout waiting for gamepad device creation
```

Workspaces Version: 1.14

**Workspace Server Information:**
```
uname -a
Linux KASM 6.5.11-7-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-7 (2023-12-05T09:44Z) x86_64 GNU/Linux
```

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
sudo docker info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.5.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dd1e886e55dd695541fdcd67420c2888645a495
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.11-7-pve
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 4GiB
 Name: KASM
 ID: 2bff7bb7-cb5d-4b39-9b26-d8b84a4879b7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

```
sudo docker ps | grep kasm
c73ff5110417   kasmweb/nginx:1.25.1       "/docker-entrypoint.…"   20 hours ago   Up 20 hours             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
d0791d828175   kasmweb/share:1.14.0       "/bin/sh -c '/usr/bi…"   20 hours ago   Up 20 hours (healthy)   8182/tcp                                        kasm_share
fe7a1504c8aa   kasmweb/agent:1.14.0       "/bin/sh -c '/usr/bi…"   20 hours ago   Up 20 hours (healthy)   4444/tcp                                        kasm_agent
52215d42ca6a   kasmweb/kasm-guac:1.14.0   "/dockerentrypoint.sh"   20 hours ago   Up 20 hours (healthy)                                                   kasm_guac
2a2928a2adc1   kasmweb/manager:1.14.0     "/bin/sh -c '/usr/bi…"   20 hours ago   Up 20 hours (healthy)   8181/tcp                                        kasm_manager
0e65d200b6db   redis:5-alpine             "docker-entrypoint.s…"   20 hours ago   Up 20 hours             6379/tcp                                        kasm_redis
917584980a73   kasmweb/api:1.14.0         "/bin/sh -c '/usr/bi…"   20 hours ago   Up 20 hours (healthy)   8080/tcp                                        kasm_api
214f505403af   postgres:12-alpine         "docker-entrypoint.s…"   20 hours ago   Up 20 hours (healthy)   5432/tcp                                        kasm_db
```

The issue is reproducible in any supported OS if Kasm Workspaces is run in an LXC container. Not reproducible if it's run in a VM. Disabling allow_kasm_gamepad option resolves the issue but the Gamepad pass-through is obviously not functional.

**Comment by evk404** [comment]
Tried to pass-through /dev/uinput from the host machine to LXC. It didn't help. The workspace was still unable to start but the error message changed. Now it's just an unhandled exception.
```
host: KASM
ingest_date: 202401042300
application: kasm_api
levelname: ERROR
kasm_user_name: evk
process: client_api_server
client_ip: 192.168.101.100
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
message
Error during Create request for Server(f9836345-9935-41c4-9f30-61d0b7bf52db) : (Exception creating Kasm: Traceback (most recent call last):
  File "__init__.py", line 539, in post
  File "provision.py", line 1494, in provision
Exception: Could not create gamepad devices
)
```

**Comment by martindimitrov-taulia** [comment]
Yesterday I tried exactly the same. Got exactly the same results. :). I also tried from MacOS client and with different browsers. It appears that the gamepad is detected if I open locally a HTML5 based page for gamepad testing however it's not detected by Kasm. I'm not sure if this could be due to the LXC, somebody could tell. If I have some time I would test with local installation without LXC.

**Comment by evk404** [comment]
This is a server-side issue and it's most certainly related to the LXC. I tried to run it in a VM instead of LXC, on the same Proxmox node, and everything worked just fine, even when I accessed it from the same browser.
The question is - how to configure LXC properly. I'm not even sure it's possible. As I mentioned earlier, I tried to setup the pass-through of /dev/uinput device into the LXC. It still didn't work but the error message was different.
Running it in a VM instead of LXC is a viable option but I'm concerned about the performance overhead. I gave it a shot but, for instance, Retroarch was very laggy even with NES emulation.

**Comment by evk404** [comment]
After some additional research I found that in theory the Gamepad Helper Container needs access to more resources of the host machine:
1. /dev/uinput has to be available
2. /dev/input directory has to be available
3. /run/udev/data has to be available

I was able to passthrough /dev/uinput  and to mount /dev/input to the LXC. But I have no idea how to make /run/udev/data available in the LXC. I was unable to mount it to the LXC as a directory. I've found no useful information on that matter.

**Comment by j-travis** [comment]
Thanks for reporting the issue.

The official recommendation is to run Workspaces on a VM or Hardware.  We do not test/QC against running Kasm within an LXC or another docker container.

Linuxserver.io has an unofficial image of Kasm running inside another docker container you may get hints from. You can see they are defining various volumes for the gamepad support.
https://docs.linuxserver.io/images/docker-kasm/#docker-compose-recommended-click-here-for-more-info
