### ISSUE TITLE
Persistent profile error for new session

### ISSUE THREAD

**Issue by roma-ms** [kasmtech/workspaces-issues#508]
### Existing Resources

- [ ] Please search the existing issues for related problems
- [ ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
New users cant create persistent profile when they do they try the get various error messages e.g
gateway error  

**To Reproduce**
1. Go to  persistent profile  "enabled" 
2. Click on ' launch session

2024-01-22 11:52:45,256 [DEBUG] __main__.handler: Creating container image (sha256:1434dac6cef65194209b814e41fd2d1f57cec3381ee5ccaf6ad1203483489583) name (kasm_volume_helper_dd8485) to process volume mapping (/efs/kasm_user_share/*)
2024-01-22 11:52:45,822 [DEBUG] __main__.handler: Processing of volume (/efs/kasm_user_share/*) for container (a4bee85136740ff5ab9c5c49ef7f8ce27e76c046216fb8911e8a66abc2b9892d) succeeded. + RESET=False
+ mkdir -p /host_root/efs/*
+ '[' False == True ']'
+ chown 1000:1000 /host_root/efs/kasm_user_share/*
+ ls -ld /host_root/efs/kasm_user_share/*
drwxrwxrwx. 16 kasm kasm 6144 Jan 17 12:56 /host_root/efs/kasm_user_share/*

2024-01-22 11:52:45,824 [DEBUG] __main__.handler: Removing temporary volume container: (a4bee85136740ff5ab9c5c49ef7f8ce27e76c046216fb8911e8a66abc2b9892d)
2024-01-22 11:52:45,835 [DEBUG] __main__.handler: Persistent profile volume processing for (/efs/kasm_user_share/*) succeeded
2024-01-22 11:52:46,259 [INFO] __main__.handler: container_networks dict_keys(['kasm_default_network'])
2024-01-22 11:52:46,263 [DEBUG] __main__.handler: kasm_proxy_networks dict_keys(['kasm_default_network'])
2024-01-22 11:52:46,264 [DEBUG] __main__.handler: Kasm proxy container already connected to network kasm_default_network
2024-01-22 11:52:46,268 [INFO] __main__.handler: Found kasm_proxy_ip (*:443) for network (kasm_default_network)
2024-01-22 11:52:46,271 [DEBUG] __main__.handler: generate_nginx_config
2024-01-22 11:52:46,355 [DEBUG] __main__.handler: Nginx reload successful (2024/01/22 11:52:46 [warn] 711#711: "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/certs/kasm_nginx.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/certs/kasm_nginx.crt"
2024/01/22 11:52:46 [notice] 711#711: signal process started
)
2024-01-22 11:52:46,377 [DEBUG] __main__.handler: Executing kasm_post_run_user.sh
2024-01-22 11:52:46,464 [ERROR] __main__.handler: Error after container creation Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.44/containers/44cc41e86c3b478f335abfa8a4ea881f8ac843421b5800230e87b67dc13c60fc/exec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "provision.py", line 776, in provision
  File "docker/models/containers.py", line 193, in exec_run
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/exec_api.py", line 80, in exec_create
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.44/containers/44cc41e86c3b478f335abfa8a4ea881f8ac843421b5800230e87b67dc13c60fc/exec: Conflict ("Container 44cc41e86c3b478f335abfa8a4ea881f8ac843421b5800230e87b67dc13c60fc is restarting, wait until the container is running")
Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.44/containers/44cc41e86c3b478f335abfa8a4ea881f8ac843421b5800230e87b67dc13c60fc/exec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "provision.py", line 776, in provision
  File "docker/models/containers.py", line 193, in exec_run
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/exec_api.py", line 80, in exec_create
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.44/containers/44cc41e86c3b478f335abfa8a4ea881f8ac843421b5800230e87b67dc13c60fc/exec: Conflict ("Container 44cc41e86c3b478f335abfa8a4ea881f8ac843421b5800230e87b67dc13c60fc is restarting, wait until the container is running")
2024-01-22 11:52:46,467 [DEBUG] __main__.handler: destroy
2024-01-22 11:52:46,816 [INFO] __main__.handler: Removing Existing Container 44cc41e86c3b478f335abfa8a4ea881f8ac843421b5800230e87b67dc13c60fc
2024-01-22 11:52:46,817 [INFO] __main__.handler: Skipping shutdown script
2024-01-22 11:52:46,983 [DEBUG] __main__.handler: remove_nginx_config
2024-01-22 11:52:47,057 [DEBUG] __main__.handler: Nginx reload successful (2024/01/22 11:52:47 [warn] 733#733: "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/certs/kasm_nginx.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/certs/kasm_nginx.crt"
2024/01/22 11:52:47 [notice] 733#733: signal process started
)
2024-01-22 11:52:47,059 [DEBUG] __main__.handler: Searching for docker networks to prune
2024-01-22 11:52:47,059 [DEBUG] __main__.handler: get_container_by_id
2024-01-22 11:52:47,060 [DEBUG] __main__.handler: Getting Container (kasm_proxy)
2024-01-22 11:52:47,064 [INFO] __main__.handler: Container ID (44cc41e86c3b478f335abfa8a4ea881f8ac843421b5800230e87b67dc13c60fc) Not Found
2024-01-22 11:52:47,066 [ERROR] __main__.handler: Exception creating Kasm: Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.44/containers/44cc41e86c3b478f335abfa8a4ea881f8ac843421b5800230e87b67dc13c60fc/exec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__init__.py", line 481, in post
  File "provision.py", line 776, in provision
  File "docker/models/containers.py", line 193, in exec_run
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/exec_api.py", line 80, in exec_create
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.44/containers/44cc41e86c3b478f335abfa8a4ea881f8ac843421b5800230e87b67dc13c60fc/exec: Conflict ("Container 44cc41e86c3b478f335abfa8a4ea881f8ac843421b5800230e87b67dc13c60fc is restarting, wait until the container is running")
Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.44/containers/44cc41e86c3b478f335abfa8a4ea881f8ac843421b5800230e87b67dc13c60fc/exec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__init__.py", line 481, in post
  File "provision.py", line 776, in provision
  File "docker/models/containers.py", line 193, in exec_run
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/exec_api.py", line 80, in exec_create
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.44/containers/44cc41e86c3b478f335abfa8a4ea881f8ac843421b5800230e87b67dc13c60fc/exec: Conflict ("Container 44cc41e86c3b478f335abfa8a4ea881f8ac843421b5800230e87b67dc13c60fc is restarting, wait until the container is running")

2024-01-22 12:05:49,277 [DEBUG] __main__.handler: Image (xxxxxxxx) is present. No hash specified for verification
2024-01-22 12:05:49,278 [DEBUG] __main__.handler: provision
2024-01-22 12:05:49,279 [DEBUG] __main__.handler: Creating container image (sha256:1434dac6cef65194209b814e41fd2d1f57cec3381ee5ccaf6ad1203483489583) name (kasm_volume_helper_cebfbf) to process volume mapping (/efs/kasm_user_share/xxxxxxxxxx)
2024-01-22 12:05:49,831 [DEBUG] __main__.handler: Processing of volume (/efs/kasm_user_share/xxxxxxx) for container (3bf7506e30a871402d077abbc7478601d32f806cf3af6e162177cbcd2a2d80a3) succeeded. + RESET=False
+ mkdir -p /host_root/efs/xxxxxxxxx/
+ '[' False == True ']'
+ chown 1000:1000 /host_root/efs/kasm_user_share/xxxxxxxxxx

2024-01-22 12:05:49,832 [DEBUG] __main__.handler: Removing temporary volume container: (3bf7506e30a871402d077abbc7478601d32f806cf3af6e162177cbcd2a2d80a3)
2024-01-22 12:05:49,843 [DEBUG] __main__.handler: Persistent profile volume processing for (/efs/kasm_user_share/****) succeeded
2024-01-22 12:05:50,256 [INFO] __main__.handler: container_networks dict_keys(['kasm_default_network'])
2024-01-22 12:05:50,260 [DEBUG] __main__.handler: kasm_proxy_networks dict_keys(['kasm_default_network'])
2024-01-22 12:05:50,260 [DEBUG] __main__.handler: Kasm proxy container already connected to network kasm_default_network
2024-01-22 12:05:50,265 [INFO] __main__.handler: Found kasm_proxy_ip (172.18.0.2:443) for network (kasm_default_network)
2024-01-22 12:05:50,266 [DEBUG] __main__.handler: generate_nginx_config
2024-01-22 12:05:50,355 [DEBUG] __main__.handler: Nginx reload successful (2024/01/22 12:05:50 [warn] 758#758: "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/certs/kasm_nginx.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/certs/kasm_nginx.crt"
2024/01/22 12:05:50 [notice] 758#758: signal process started
)
2024-01-22 12:05:50,385 [DEBUG] __main__.handler: Executing kasm_post_run_user.sh
2024-01-22 12:05:50,441 [ERROR] __main__.handler: Error after container creation Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.44/containers/5f834a1f1d47c2952900c96d0dcd7a560395f4156962503e91d8efc92a824363/exec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "provision.py", line 776, in provision
  File "docker/models/containers.py", line 193, in exec_run
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/exec_api.py", line 80, in exec_create
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.44/containers/5f834a1f1d47c2952900c96d0dcd7a560395f4156962503e91d8efc92a824363/exec: Conflict ("Container 5f834a1f1d47c2952900c96d0dcd7a560395f4156962503e91d8efc92a824363 is restarting, wait until the container is running")
Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.44/containers/5f834a1f1d47c2952900c96d0dcd7a560395f4156962503e91d8efc92a824363/exec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "provision.py", line 776, in provision
  File "docker/models/containers.py", line 193, in exec_run
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/exec_api.py", line 80, in exec_create
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.44/containers/5f834a1f1d47c2952900c96d0dcd7a560395f4156962503e91d8efc92a824363/exec: Conflict ("Container 5f834a1f1d47c2952900c96d0dcd7a560395f4156962503e91d8efc92a824363 is restarting, wait until the container is running")
2024-01-22 12:05:50,446 [DEBUG] __main__.handler: destroy
2024-01-22 12:05:50,837 [INFO] __main__.handler: Removing Existing Container 5f834a1f1d47c2952900c96d0dcd7a560395f4156962503e91d8efc92a824363
2024-01-22 12:05:50,838 [INFO] __main__.handler: Skipping shutdown script
2024-01-22 12:05:51,007 [DEBUG] __main__.handler: remove_nginx_config
2024-01-22 12:05:51,087 [DEBUG] __main__.handler: Nginx reload successful (2024/01/22 12:05:51 [warn] 780#780: "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/certs/kasm_nginx.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/certs/kasm_nginx.crt"
2024/01/22 12:05:51 [notice] 780#780: signal process started
)
2024-01-22 12:05:51,088 [DEBUG] __main__.handler: Searching for docker networks to prune
2024-01-22 12:05:51,089 [DEBUG] __main__.handler: get_container_by_id
2024-01-22 12:05:51,089 [DEBUG] __main__.handler: Getting Container (kasm_proxy)
2024-01-22 12:05:51,093 [INFO] __main__.handler: Container ID (5f834a1f1d47c2952900c96d0dcd7a560395f4156962503e91d8efc92a824363) Not Found
2024-01-22 12:05:51,094 [ERROR] __main__.handler: Exception creating Kasm: Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.44/containers/5f834a1f1d47c2952900c96d0dcd7a560395f4156962503e91d8efc92a824363/exec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__init__.py", line 481, in post
  File "provision.py", line 776, in provision
  File "docker/models/containers.py", line 193, in exec_run
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/exec_api.py", line 80, in exec_create
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.44/containers/5f834a1f1d47c2952900c96d0dcd7a560395f4156962503e91d8efc92a824363/exec: Conflict ("Container 5f834a1f1d47c2952900c96d0dcd7a560395f4156962503e91d8efc92a824363 is restarting, wait until the container is running")
Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.44/containers/5f834a1f1d47c2952900c96d0dcd7a560395f4156962503e91d8efc92a824363/exec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__init__.py", line 481, in post
  File "provision.py", line 776, in provision
  File "docker/models/containers.py", line 193, in exec_run
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/exec_api.py", line 80, in exec_create
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.44/containers/5f834a1f1d47c2952900c96d0dcd7a560395f4156962503e91d8efc92a824363/exec: Conflict ("Container 5f834a1f1d47c2952900c96d0dcd7a560395f4156962503e91d8efc92a824363 is restarting, wait until the container is running")
**Expected behavior**
A new session should open 

**Screenshots**

![Screenshot 2024-01-22 at 12 24 41](https://github.com/kasmtech/workspaces-issues/assets/36697343/e5fc0952-385e-4c7f-8c56-9092f5b75031)

**Workspaces Version**
e.g Version 1.12

**Workspaces Installation Method**
terraform 

**Client Browser (please complete the following information):**
 - OS:  both Windows and  IOS
 - Browser All  chrome, safari firefox

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
 - `cat /etc/os-release`
 - `sudo docker info`
 - `sudo docker ps | grep kasm`

**Additional context**

**Comment by j-travis** [comment]
I recommend reading over our NFS setup guide, in particular the specifics we demonstrate in the /etc/exports
https://kasmweb.com/docs/latest/guide/persistent_data/host_guides.html#host-configuration-guides

And also the tests for creating a file via sudo and verify the permissions are correct on the file after being created (1000) 

You'll want to verify you can setup EFS or the mount with the `all_squash,anonuid=1000,anongid=1000,no_subtree_check` or equivalent 

Once you get that working, try creating a new session.

If it still fails you can use these steps to take a look at the session container logs:
https://github.com/kasmtech/workspaces-issues/issues/444#issuecomment-1736460285

**Comment by teja-kasm** [comment]
We’re currently enhancing our GitHub issue tracker to improve organization and efficiency.

As part of this process, we’re closing older issues to help keep the tracker focused on current and active topics.

If this issue is still relevant or you’re still experiencing the problem, please feel free to create a new issue.

Thank you for your understanding!
