### ISSUE TITLE
[Bug] - Starting the signal workspace starts the container but it fails to create a QR code for login. 

### ISSUE THREAD

**Issue by gtgcerint** [kasmtech/workspaces-issues#515]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
Starting the signal workspace starts the container but it fails to create a QR code for login. 

**To Reproduce**
Start the signal workspace 
Wait for the QR code to load
it will display an error

**Expected behavior**
Expected to genrate a QR code

**Screenshots**
![image](https://github.com/kasmtech/workspaces-issues/assets/63113549/f36b2cfb-bd17-4813-b049-92faef63d850)

**Workspaces Version**
Version 1.14
kasmweb/signal:1.14.0

**Workspaces Installation Method**
Single Server

**Client Browser (please complete the following information):**
 - OS: Windows
 - Browser chrome, firefox
 - Version Latest

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
 - 
![image](https://github.com/kasmtech/workspaces-issues/assets/63113549/e7047f0b-9a94-4457-aa4f-70dd594981cf)

 - `cat /etc/os-release`
 - 
![image](https://github.com/kasmtech/workspaces-issues/assets/63113549/c13329ad-a8c3-44ce-ad6c-a41ad74957c6)

 - `sudo docker info`
 - 
![image](https://github.com/kasmtech/workspaces-issues/assets/63113549/98454c06-96a9-47a0-b4f5-9ef2366ad0d7)

 - `sudo docker ps | grep kasm`
 - 
![image](https://github.com/kasmtech/workspaces-issues/assets/63113549/2890d2a8-f242-40b6-83bc-bcd30e56cedd)

**Additional context**
If i start the ubuntu Jammy workspace and start the signal app in there i get the same problem. However if i run update and upgrade inside the ubuntu workspace then the signal app works. I wonder if the docker image for kasm/signal needs an update.

**Comment by j-travis** [comment]
Try updating your workspace entry for signal to use the "rolling" tag which is updated daily

```
kasmweb/signal:1.14.0-rolling
```

You can do the same for the other images if you wish

**Comment by gtgcerint** [comment]
I tried that but unfortunately, the update fails because it can't get the image. 

Error Getting Image: (kasmweb/signal:1.14.0-rolling) : 401 Client Error for http+docker://localhost/v1.44/auth: Unauthorized ("Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password") 
Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http+docker://localhost/v1.44/auth

**Comment by gtgcerint** [comment]
I made a workaround for this. I am spinning up a ubuntu instance and run:
sudo apt update && sudo apt install signal-desktop

then i can use signal from within the ubuntu instance. It takes a lot more resources but its a way.

**Comment by kachunkachunk** [comment]
FWIW, I seemed to have no issues with the kasmweb/signal:1.14.0-rolling release/tag, and did not face the same authentication errors. But I can confirm having the same issue as reported; the QR code generation times out and you can't link the client on the normal 1.14.0 release. Rolling has had sorted it out somewhere, though.

That said, I assume you used persistent profiles for your Ubuntu workspace? If so, maybe you can configure the same persistent profile path for the Signal workspace/image and see if it'll come up already linked.

Edit: You may run into database versioning errors. At least from a basic test getting the rolling update to work, I can't use the original 1.14.0 image on my persistent profile. But I think _in concept_ my suggestion could be considered while devising a better workaround.

**Comment by sts64** [comment]
Similar issue.

I cannot get Signal, as a standalone image, or through Ubuntu to run. I have tried using the -rolling tags but this makes no difference.
<img width="703" alt="signal-kasm-error" src="https://github.com/user-attachments/assets/3dfb48b4-a661-4f4b-b23d-5cf9f9686938">

Deleting a restarting does not fix the problem.

Kasm version 1.15.0
Ubuntu Server 24.04 LTS

My current workaround:

Create an executable file in file mapping for the workspace.
<img width="1221" alt="Screenshot 2024-08-29 192734" src="https://github.com/user-attachments/assets/3437530a-eee6-475c-b2e8-89678f442b0f">


Main body: 
```
#!/usr/bin/env bash
set -ex
apt-get update
apt-get install -y signal-desktop
notify-send "Script Complete" "signal is now installed"
```

Destination path:
`/dockerstartup/kasm_post_run_root.sh`

**Comment by j-travis** [comment]
Looks like signal pushed a bad update which is causing the DB error. They've released a patch today so the rolling tags should pick it up tomorrow:
https://github.com/signalapp/Signal-Desktop/issues/6996

**Comment by teja-kasm** [comment]
We’re currently enhancing our GitHub issue tracker to improve organization and efficiency.

As part of this process, we’re closing older issues to help keep the tracker focused on current and active topics.

If this issue is still relevant or you’re still experiencing the problem, please feel free to create a new issue.

Thank you for your understanding!
