### ISSUE TITLE
New Install Community Edition on Virtual Box VM - Ubuntu 22.0.4

### ISSUE THREAD

**Issue by DTech33** [kasmtech/workspaces-issues#531]
New built vm with Ubuntu22.04 and installed latest community edition. When I try to download chrome image.  It fails with..

Failed to pull image (kasmweb/chrome:1.15.0) : 404 Client Error for http+docker://localhost/v1.44/images/kasmweb/chrome:1.15.0/json: Not Found ("No such image: kasmweb/chrome:1.15.0") Traceback (most recent call last): File "docker/api/client.py", line 268, in _raise_for_status File "requests/models.py", line 1021, in raise_for_status requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.44/images/kasmweb/chrome:1.15.0/json During handling of the above exception, another exception occurred: Traceback (most recent call last): File "provision.py", line 2209, in get_image File "docker/models/images.py", line 455, in pull File "docker/models/images.py", line 316, in get File "docker/utils/decorators.py", line 19, in wrapped File "docker/api/image.py", line 253, in inspect_image File "docker/api/client.py", line 274, in _result File "docker/api/client.py", line 270, in _raise_for_status File "docker/errors.py", line 31, in create_api_error_from_http_exception docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.44/images/kasmweb/chrome:1.15.0/json: Not Found ("No such image: kasmweb/chrome:1.15.0")

The virtual box unbuntu is set to bridge adapter mode. Do I need to do anything with the docker/kasm proxy? or am I missing something else.

**Comment by j-travis** [comment]
This sounds like a host/VM configuration issue. Ensure you don't have any firewall rules that are blocking web/dns access from the docker network subnets

**Comment by teja-kasm** [comment]
We’re currently enhancing our GitHub issue tracker to improve organization and efficiency.

As part of this process, we’re closing older issues to help keep the tracker focused on current and active topics.

If this issue is still relevant or you’re still experiencing the problem, please feel free to create a new issue.

Thank you for your understanding!
