### ISSUE TITLE
[Bug] - Not able to access containers on a ipv6 only network.

### ISSUE THREAD

**Issue by thel1988** [kasmtech/workspaces-issues#533]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
It seems that when you try to connect to a container running on a docker agent, with ipv6. It errors out with saying it is not able to connect and find a suitable hostname.

**To Reproduce**
Create a docker agent with only a AAAA-dns record in ipv6 only environment, and have it join the manager. All communication at this point is working fine. But when you try to launch a container from the web part, it will error out: 
`Unhandled exception occurred
Traceback (most recent call last):
  File "cherrypy/_cprequest.py", line 628, in respond
  File "cherrypy/_cprequest.py", line 687, in _do_respond
  File "cherrypy/lib/encoding.py", line 219, in __call__
  File "cherrypy/_cpdispatch.py", line 54, in __call__
  File "utils.py", line 490, in wrapper
  File "client_api.py", line 2392, in kasm_connect
socket.gaierror: [Errno -5] No address associated with hostname`
[log-entry-export-bug.json](https://github.com/kasmtech/workspaces-issues/files/14632192/log-entry-export-bug.json)

**Expected behavior**
Normally you should be able to launch a container from webconsole, but it just errors out when trying to connect.
We have implemented a workaround with container running socat, with the listed as the hostname in question which then forwards the request to the correct ipv6 address.
version: '3'
services:
  socat:
    init: true
    restart: always
    hostname: kasm-agent01.bug.com
    image: 'simonrupf/socat:latest'
    command: 'TCP4-LISTEN:443,fork,reuseaddr, TCP6:[2a03:xxxx:x:xxxx::xxx]:443'
    networks:
      - kasm_default_network

networks:
  kasm_default_network:
    external: true
The adress is both resolveable from the container itself and on the host, so no dns issue.

It seems it only requests a ipv4 address but not a: AAAA record.

**Screenshots**
N/A

**Workspaces Version**
Version 1.15.0

**Workspaces Installation Method**
Multi-server

**Client Browser (please complete the following information):**
- MacOSx
 - Chrome/122.0.0.0

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a xxxx 5.15.0-100-generic #110-Ubuntu SMP Wed Feb 7 13:27:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux` 
 - `cat /etc/os-release PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy`
 - `Client: Docker Engine - Community
 Version:    25.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.5.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
`
 - `sudo docker ps | grep kasm
  docker ps | grep kasm
cd4d8151ac4d   simonrupf/socat:latest   "/bin/socat TCP4-LIS…"   3 days ago   Up 3 days                                                                 kasm-socat-1
16e4221ef75d   kasmweb/nginx:1.25.3     "/docker-entrypoint.…"   3 days ago   Up 45 minutes             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
5655918f453b   kasmweb/api:1.15.0       "/bin/sh -c '/usr/bi…"   3 days ago   Up 45 minutes (healthy)   8080/tcp                                        kasm_api
86ebeaa42f2a   kasmweb/manager:1.15.0   "/bin/sh -c '/usr/bi…"   3 days ago   Up 45 minutes (healthy)   8181/tcp                                        kasm_manager
8bb761bc74eb   kasmweb/share:1.15.0     "/bin/sh -c '/usr/bi…"   3 days ago   Up 45 minutes (healthy)   8182/tcp                                        kasm_share`

**Additional context**

**Comment by teja-kasm** [comment]
We’re currently enhancing our GitHub issue tracker to improve organization and efficiency.

As part of this process, we’re closing older issues to help keep the tracker focused on current and active topics.

If this issue is still relevant or you’re still experiencing the problem, please feel free to create a new issue.

Thank you for your understanding!
