### ISSUE TITLE
i keep getting 400 Client Error from gitlab hosted Dockerfile

### ISSUE THREAD

**Issue by TeamLipra** [kasmtech/workspaces-issues#549]
i followed the steps in: https://kasmweb.com/docs/latest/how_to/building_images.html#push-to-registry, docker push worked, it also works with docker pull but when i try to pull the image through kasm i get this error: ("--" is just me manually replacing my gitlab name)

```
Error Getting Image: (https://registry.gitlab.com/--/--/custom-ubuntu:1.0.0) : 400 Client Error for /v1.45/images/https:/registry.gitlab.com/--/--/custom-ubuntu:1.0.0/json: Bad Request ("invalid reference format") 
Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: /v1.45/images/https:/registry.gitlab.com/--/--/custom-ubuntu:1.0.0/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "provision.py", line 2153, in check_images
  File "provision.py", line 917, in has_image
  File "docker/models/images.py", line 316, in get
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/image.py", line 253, in inspect_image
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 400 Client Error for /v1.45/images/https:/registry.gitlab.com/--/--/custom-ubuntu:1.0.0/json: Bad Request ("invalid reference format")
```

**Comment by TeamLipra** [comment]
nevermind, i just realizied i was stuck for 2 hours on this because i didnt remove the "https://" in front of the "registry.gitlab.com/"
