### ISSUE TITLE
Gateway Timeouts randomly in create user and create Kasm

### ISSUE THREAD

**Issue by trentmcewan** [kasmtech/workspaces-issues#568]
We are getting random gateway timeout errors when trying to create users and create kasm --- It will work for a few hours and then simply start throwing the gateway errors

<html>
<head>
    <title>504 Gateway Time-out</title>
</head>
<body>
    <center>
        <h1>504 Gateway Time-out</h1>
    </center>
    <hr>
    <center>nginx</center>
</body>
</html>
kasm logs:
Exception creating Kasm: Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 467, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3/connectionpool.py", line 462, in _make_request
  File "http/client.py", line 1348, in getresponse
  File "http/client.py", line 316, in begin
  File "http/client.py", line 277, in _read_status
  File "socket.py", line 669, in readinto
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 799, in urlopen
  File "urllib3/util/retry.py", line 550, in increment
  File "urllib3/packages/six.py", line 770, in reraise
  File "urllib3/connectionpool.py", line 715, in urlopen
  File "urllib3/connectionpool.py", line 469, in _make_request
  File "urllib3/connectionpool.py", line 358, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "__init__.py", line 573, in post
  File "provision.py", line 1683, in provision
  File "provision.py", line 1540, in process_storage_mapping
  File "provision.py", line 1534, in process_storage_mapping
  File "docker/models/volumes.py", line 57, in create
  File "docker/api/volume.py", line 89, in create_volume
  File "docker/api/client.py", line 296, in _post_json
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 233, in _post
  File "requests/sessions.py", line 637, in post
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 532, in send
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 467, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3/connectionpool.py", line 462, in _make_request
  File "http/client.py", line 1348, in getresponse
  File "http/client.py", line 316, in begin
  File "http/client.py", line 277, in _read_status
  File "socket.py", line 669, in readinto
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 799, in urlopen
  File "urllib3/util/retry.py", line 550, in increment
  File "urllib3/packages/six.py", line 770, in reraise
  File "urllib3/connectionpool.py", line 715, in urlopen
  File "urllib3/connectionpool.py", line 469, in _make_request
  File "urllib3/connectionpool.py", line 358, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "__init__.py", line 573, in post
  File "provision.py", line 1683, in provision
  File "provision.py", line 1540, in process_storage_mapping
  File "provision.py", line 1534, in process_storage_mapping
  File "docker/models/volumes.py", line 57, in create
  File "docker/api/volume.py", line 89, in create_volume
  File "docker/api/client.py", line 296, in _post_json
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 233, in _post
  File "requests/sessions.py", line 637, in post
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 532, in send
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)..

**Comment by trentmcewan** [comment]
Error during Create request for Server(8ca02332-c43c-4914-92aa-cf459d34798f) : (Traceback (most recent call last):
  File "provider_manager.py", line 1832, in create_kasm_from_slot
  File "provider_manager.py", line 1738, in get_agent_request
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 531, in open
  File "urllib/request.py", line 640, in http_response
  File "urllib/request.py", line 569, in error
  File "urllib/request.py", line 502, in _call_chain
  File "urllib/request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 504: Gateway Time-out
)

**Comment by trentmcewan** [comment]
From Kasm Log
From kasmui:
Exception creating Kasm: Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 467, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3/connectionpool.py", line 462, in _make_request
  File "http/client.py", line 1348, in getresponse
  File "http/client.py", line 316, in begin
  File "http/client.py", line 277, in _read_status
  File "socket.py", line 669, in readinto
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 799, in urlopen
  File "urllib3/util/retry.py", line 550, in increment
  File "urllib3/packages/six.py", line 770, in reraise
  File "urllib3/connectionpool.py", line 715, in urlopen
  File "urllib3/connectionpool.py", line 469, in _make_request
  File "urllib3/connectionpool.py", line 358, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "__init__.py", line 573, in post
  File "provision.py", line 1683, in provision
  File "provision.py", line 1540, in process_storage_mapping
  File "provision.py", line 1534, in process_storage_mapping
  File "docker/models/volumes.py", line 57, in create
  File "docker/api/volume.py", line 89, in create_volume
  File "docker/api/client.py", line 296, in _post_json
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 233, in _post
  File "requests/sessions.py", line 637, in post
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 532, in send
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 467, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3/connectionpool.py", line 462, in _make_request
  File "http/client.py", line 1348, in getresponse
  File "http/client.py", line 316, in begin
  File "http/client.py", line 277, in _read_status
  File "socket.py", line 669, in readinto
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 799, in urlopen
  File "urllib3/util/retry.py", line 550, in increment
  File "urllib3/packages/six.py", line 770, in reraise
  File "urllib3/connectionpool.py", line 715, in urlopen
  File "urllib3/connectionpool.py", line 469, in _make_request
  File "urllib3/connectionpool.py", line 358, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "__init__.py", line 573, in post
  File "provision.py", line 1683, in provision
  File "provision.py", line 1540, in process_storage_mapping
  File "provision.py", line 1534, in process_storage_mapping
  File "docker/models/volumes.py", line 57, in create
  File "docker/api/volume.py", line 89, in create_volume
  File "docker/api/client.py", line 296, in _post_json
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 233, in _post
  File "requests/sessions.py", line 637, in post
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 532, in send
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)



From Azure Log

2024-06-03T18:21:03Z   [Information]   RequesKasm body={"api_key":"xUPVzTZtL6p8","api_key_secret":"LogL8ifZBp5YLCWj6H9f5SSmckNSmsd6","user_id":"1de1786b766647bfa9f352412de708fb","image_id":"b6274e5da9fa4df883c8693c49c34d08","enable_sharing":true}
2024-06-03T18:22:17Z   [Information]   Request kasm call done shared
2024-06-03T18:22:17Z   [Information]   Executed 'HttpFunction' (Succeeded, Id=56b54cd7-762b-40fb-ab12-c4c4ee141062, Duration=74523ms)

**Comment by j-travis** [comment]
When you entered the ticket, we asked to provide a set of information. This data helps the community help you since it orients them to the operating environment.

https://github.com/kasmtech/workspaces-issues/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBug%5D+-+Example

Please provide the requested information, and any other details about your setup that may be helpful such as other infrastructure device , firewalls , proxies etc
