### ISSUE TITLE
[Bug] - kasm_guac - unhealthy - ERROR guac [server] Healthcheck failed

### ISSUE THREAD

**Issue by fanuelsen** [kasmtech/workspaces-issues#571]
### Existing Resources

- [X] Please search the existing issues for related problems
- [X] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [X] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [X] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [X] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
After upgrading kasm (from 1.11 to 1.15) with the autoupgrade script the kasm_guac container is unhealthy. Workspaces is still working so i'm not sure what guac_server is used for. But the following output is inside the kasm_guac container.

`2024-06-05 09:05:43,516 INFO guac [server] Registering kasm_guac with configuration: {
  "target_component": {
    "type": "connection_proxy",
    "server_address": "proxy",
    "server_port": 443,
    "zone_name": "default"
  },
  "registration_token": "**********",
  "token": "JWTTOKEN"
}
2024-06-05 09:05:43,516 INFO guac [server] Attempt 1/10 attempts
2024-06-05 09:05:43,850 ERROR guac [server] Healthcheck failed for "proxy". Error: Request failed with status code 502
2024-06-05 09:05:43,858 ERROR guac [server] Healthcheck failed for "kasm_proxy". Error: Request failed with status code 502
2024-06-05 09:05:45,861 INFO guac [server] Attempt 2/10 attempts
ComponentRegistrationError: Access Denied!
    at Object.registerWithDeployment (/gclient/kasm.js:81:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/gclient/server.js:242:5)
    at async run (/gclient/app.js:12:5)`

**Expected behavior**
Should start as expected.

**Workspaces Version**
Version 1.15

**Workspaces Installation Method**
Single Server

**Workspace Server Information (please provide the output of the following commands):**
 - `5.4.0-42-generic #46-Ubuntu SMP`
 - `VERSION="20.04.6 LTS (Focal Fossa)`
 - `Client: Docker Engine - Community Version:    26.1.3`
 - `9b4ab264c7b0   kasmweb/nginx:1.25.3       "/docker-entrypoint.…"   2 hours ago   Up 55 minutes               80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
cae8635b7258   kasmweb/agent:1.15.0       "/bin/sh -c '/usr/bi…"   2 hours ago   Up 55 minutes (healthy)     4444/tcp                                        kasm_agent
5fff30b34f64   kasmweb/share:1.15.0       "/bin/sh -c '/usr/bi…"   2 hours ago   Up 55 minutes (healthy)     8182/tcp                                        kasm_share
e4b2fdabc794   kasmweb/api:1.15.0         "/bin/sh -c '/usr/bi…"   2 hours ago   Up 55 minutes (healthy)     8080/tcp                                        kasm_api
1112348b6ac7   kasmweb/manager:1.15.0     "/bin/sh -c '/usr/bi…"   2 hours ago   Up 55 minutes (healthy)     8181/tcp                                        kasm_manager
fe096764df08   redis:5-alpine             "docker-entrypoint.s…"   2 hours ago   Up 55 minutes               6379/tcp                                        kasm_redis
148b1af31d19   postgres:12-alpine         "docker-entrypoint.s…"   2 hours ago   Up 55 minutes (healthy)     5432/tcp                                        kasm_db
7ea50101632d   kasmweb/kasm-guac:1.15.0   "/dockerentrypoint.sh"   2 hours ago   Up 55 minutes (unhealthy)                                                   kasm_guac`

**Comment by j-travis** [comment]
The kasm_guac role is used when you want to connect to existing systems over RDP , SSH, or VNC.  You can try following this guide - the portions that refer to restoring the guac connection proxy.

That may clear your environment up.

https://kasmweb.atlassian.net/servicedesk/customer/kb/view/8126468

I recommend taking a backup before you do in case you need to restore

**Comment by octave21** [comment]
I experienced a similar issue with the 1.16 version. It works fine when I first install it. When I turn the server off and on again, the kasm_guac starts but goes unhealthy within 2 minutes.

Sometimes in case of heavy load of the server, the kasm_guac goes unhealthy or restarts again and again.

**Comment by j-travis** [comment]
Hi, we just released Workspaces 1.16.1 which may have fixes for this scenario. Do you have cycles to do a clean install again and see if the issue persists?

**Comment by octave21** [comment]
Hi I did installed release 1.16.1 but I am not able to conclude except that at the end the issue is solved. This is what i did : 
1. Install release 1.16.1 on a running archlinux server.  Everything is => **_OK_**
2. Reboot. After reboot the kasm_guac process goes from health:starting to unheathly within 2 minutes => **_KO_**
3. Install release 1.16.1 with **_-skip-egress_** option.  Everything is => **_OK_** 
4. Reboot. After reboot the kasm_guac process goes from health:starting to heathly within 2 minutes => **_OK_**

**Comment by matteog79** [comment]
Hi, I have the same problem, yesterday I installed Kasm on my ubuntu vm server, I configured it, after restarted the ubuntu vm server the kasm_guac docker container was found to be unhealthy, on google I found some guides to try to solve it, but nothing works, I uninstalled it, restarted the server, reinstalled kasm, restarted the server again, after restart same problem with the kasm_guac docker container, it was unhealthy. No solution to fix at the moment, do you have any suggestions to fix the problem?

thank you very much

Latest version of KASM 1.16.1

**Comment by gc4g40u6** [comment]
Had similar issue and noticed the auth_token and public_jwt_cert was invalid in /opt/kasm/current/conf/app/kasmguac.app.config.yaml, copied them from /opt/kasm/current/conf/app/rdp_https_gateway.app.config.yaml and restarted kasm_guac - this fixed the issue for me.

**Comment by Majoraslayer** [comment]
> Had similar issue and noticed the auth_token and public_jwt_cert was invalid in /opt/kasm/current/conf/app/kasmguac.app.config.yaml, copied them from /opt/kasm/current/conf/app/rdp_https_gateway.app.config.yaml and restarted kasm_guac - this fixed the issue for me.

I had the same issue, and this right here was the fix.  auth_token and public_jwt_cert were both set to "false" in kasmguac.app.config.yaml.  Changing them to the values from rdp_https_gateway.app.config.yaml worked for me too.

**Comment by guruuno** [comment]
Having the same issue, however, not really clear on when you state: "this right here was the fix. auth_token and public_jwt_cert were both set to "false" in kasmguac.app.config.yaml. Changing them to the values from rdp_https_gateway.app.config.yaml worked"

In my config files, the rdp_https_gateway.app.config.yaml only references the word false in the line
kubernetes: false

And in the kasmguac.app.config.yaml file the only word that references false is in the line
ephemeral: false
and the only word that references true is at the end of the auth_token: >-
after the actual key the line
allow_self_signed_cert:true

There is no other reference to the words true or false in either of the referenced files

However, I do additionally see that the auth_token is different in each file but the public_jwt_cert: is identical.

Could that be the issue?

**Comment by gc4g40u6** [comment]
i would suggest you to take a backup for both yamls, copy the auth_token from rdp_https_gateway.app.config.yaml and replace the auth_token in /opt/kasm/current/conf/app/kasmguac.app.config.yaml.

**Comment by guruuno** [comment]
Thanks....did a reinstall, solved

**Comment by teja-kasm** [comment]
We’re currently enhancing our GitHub issue tracker to improve organization and efficiency.

As part of this process, we’re closing older issues to help keep the tracker focused on current and active topics.

If this issue is still relevant or you’re still experiencing the problem, please feel free to create a new issue.

Thank you for your understanding!
