### ISSUE TITLE
[Bug] - "No Resource" message versus "Progress Bar"

### ISSUE THREAD

**Issue by jm1021** [kasmtech/workspaces-issues#611]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
According to Kasm GPT I get this description about a progress tracker.

Autoscaling Feature: Kasm Workspaces v1.14 introduced the ability to provision autoscaled resources on the fly. This means that when resources are not immediately available, the system will automatically scale up to meet the demand.
User Experience: Previously, users would receive a message stating that no resources were available. With the new autoscaling feature, users will see a progress tracker as the infrastructure is being deployed to service their request.

**To Reproduce**
1. Load agents to exceed standby resource quickly
2. After resources are exhausted and scaling has not caught up, sliding red box telling No Resources appears at launch.

**Expected behavior**
I am hoping for more friendly progress bar that indicates resource is being created.

**Screenshots**
Red Box
![image](https://github.com/user-attachments/assets/421ae310-1f5d-45b0-8d02-2b1dcde51681)

Pool is growing with Null item
![image](https://github.com/user-attachments/assets/34071fe5-69fd-4c19-b6ff-51fa631481d8)

**Workspaces Version**
Version 1.15
ubuntu@ip-172-31-42-43:~$ sudo docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED       STATUS                PORTS                                               NAMES
1ae7af29bae0   kasmweb/nginx:1.25.3     "/docker-entrypoint.…"   5 weeks ago   Up 2 days             80/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp   kasm_proxy
7523b80173a1   kasmweb/manager:1.15.0   "/bin/sh -c '/usr/bi…"   5 weeks ago   Up 2 days (healthy)   8181/tcp                                            kasm_manager
d44e4205f73e   kasmweb/api:1.15.0       "/bin/sh -c '/usr/bi…"   5 weeks ago   Up 2 days (healthy)   8080/tcp                                            kasm_api
3087d9796568   kasmweb/share:1.15.0     "/bin/sh -c '/usr/bi…"   5 weeks ago   Up 2 days (healthy)   8182/tcp                                            kasm_share

**Workspaces Installation Method**
 Multi-Server

**Client Browser (please complete the following information):**
 chrome and safari

**Workspace Server Information (please provide the output of the following commands):**
 buntu@ip-172-31-42-43:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

**Additional context**
Is there a configuration that disabled progress bar?

**Comment by jm1021** [comment]
This can be repeated by having a standby schedule 0 - core, gpu, memory.  Progress bar starts on initial resource but after halting resource after 20 minutes...  The Docker Agent remains and is in blocking state.


tail of /var/log on created resource

```text
Sep  3 12:54:19 ip-172-31-42-86 networkd-dispatcher[451]: WARNING:Unknown index 83 seen, reloading interface list
Sep  3 12:54:19 ip-172-31-42-86 systemd-udevd[13504]: Using default interface naming scheme 'v249'.
Sep  3 12:54:19 ip-172-31-42-86 systemd-udevd[13503]: Using default interface naming scheme 'v249'.
Sep  3 12:54:19 ip-172-31-42-86 kernel: [ 1769.774757] br-cdce814ea1eb: port 2(veth3b0b27d) entered blocking state
Sep  3 12:54:19 ip-172-31-42-86 kernel: [ 1769.774772] br-cdce814ea1eb: port 2(veth3b0b27d) entered disabled state
Sep  3 12:54:19 ip-172-31-42-86 kernel: [ 1769.774799] veth3b0b27d: entered allmulticast mode
Sep  3 12:54:19 ip-172-31-42-86 kernel: [ 1769.776229] veth3b0b27d: entered promiscuous mode
Sep  3 12:54:19 ip-172-31-42-86 systemd-networkd[335]: veth3b0b27d: Link UP
Sep  3 12:54:19 ip-172-31-42-86 dockerd[5230]: time="2024-09-03T12:54:19.149143387Z" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers"
Sep  3 12:54:19 ip-172-31-42-86 containerd[5077]: time="2024-09-03T12:54:19.237685208Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
Sep  3 12:54:19 ip-172-31-42-86 containerd[5077]: time="2024-09-03T12:54:19.238390176Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
Sep  3 12:54:19 ip-172-31-42-86 containerd[5077]: time="2024-09-03T12:54:19.238407276Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
Sep  3 12:54:19 ip-172-31-42-86 containerd[5077]: time="2024-09-03T12:54:19.238518024Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.pause\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
Sep  3 12:54:19 ip-172-31-42-86 systemd[1]: Started libcontainer container 28dd63ae17a6fa5febe37f9f0ff13a05e51c167fac420374fd78680bc9ab0155.
Sep  3 12:54:19 ip-172-31-42-86 kernel: [ 1770.064485] eth0: renamed from vethe18a408
Sep  3 12:54:19 ip-172-31-42-86 systemd-networkd[335]: veth3b0b27d: Gained carrier
Sep  3 12:54:19 ip-172-31-42-86 kernel: [ 1770.085850] br-cdce814ea1eb: port 2(veth3b0b27d) entered blocking state
Sep  3 12:54:19 ip-172-31-42-86 kernel: [ 1770.085858] br-cdce814ea1eb: port 2(veth3b0b27d) entered forwarding state
Sep  3 12:54:19 ip-172-31-42-86 systemd[1]: docker-28dd63ae17a6fa5febe37f9f0ff13a05e51c167fac420374fd78680bc9ab0155.scope: Deactivated successfully.
Sep  3 12:54:19 ip-172-31-42-86 dockerd[5230]: time="2024-09-03T12:54:19.519394652Z" level=info msg="ignoring event" container=28dd63ae17a6fa5febe37f9f0ff13a05e51c167fac420374fd78680bc9ab0155 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Sep  3 12:54:19 ip-172-31-42-86 containerd[5077]: time="2024-09-03T12:54:19.519863171Z" level=info msg="shim disconnected" id=28dd63ae17a6fa5febe37f9f0ff13a05e51c167fac420374fd78680bc9ab0155 namespace=moby
Sep  3 12:54:19 ip-172-31-42-86 containerd[5077]: time="2024-09-03T12:54:19.520278215Z" level=warning msg="cleaning up after shim disconnected" id=28dd63ae17a6fa5febe37f9f0ff13a05e51c167fac420374fd78680bc9ab0155 namespace=moby
Sep  3 12:54:19 ip-172-31-42-86 containerd[5077]: time="2024-09-03T12:54:19.520298286Z" level=info msg="cleaning up dead shim" namespace=moby
Sep  3 12:54:19 ip-172-31-42-86 systemd-networkd[335]: veth3b0b27d: Lost carrier
Sep  3 12:54:19 ip-172-31-42-86 kernel: [ 1770.249822] br-cdce814ea1eb: port 2(veth3b0b27d) entered disabled state
Sep  3 12:54:19 ip-172-31-42-86 kernel: [ 1770.250192] vethe18a408: renamed from eth0
Sep  3 12:54:19 ip-172-31-42-86 systemd-udevd[13512]: Using default interface naming scheme 'v249'.
Sep  3 12:54:19 ip-172-31-42-86 networkd-dispatcher[451]: WARNING:Unknown index 83 seen, reloading interface list
Sep  3 12:54:19 ip-172-31-42-86 systemd-networkd[335]: veth3b0b27d: Link DOWN
Sep  3 12:54:19 ip-172-31-42-86 kernel: [ 1770.286672] br-cdce814ea1eb: port 2(veth3b0b27d) entered disabled state
Sep  3 12:54:19 ip-172-31-42-86 kernel: [ 1770.288037] veth3b0b27d (unregistering): left allmulticast mode
Sep  3 12:54:19 ip-172-31-42-86 kernel: [ 1770.288043] veth3b0b27d (unregistering): left promiscuous mode
Sep  3 12:54:19 ip-172-31-42-86 kernel: [ 1770.288049] br-cdce814ea1eb: port 2(veth3b0b27d) entered disabled state
Sep  3 12:54:19 ip-172-31-42-86 networkd-dispatcher[451]: ERROR:Unknown interface index 83 seen even after reload
Sep  3 12:54:19 ip-172-31-42-86 networkctl[13632]: Interface "veth3b0b27d" not found.
Sep  3 12:54:19 ip-172-31-42-86 systemd[1]: networkd-dispatcher.service: Got notification message from PID 13632, but reception only permitted for main PID 451
Sep  3 12:54:19 ip-172-31-42-86 networkd-dispatcher[451]: ERROR:Failed to get interface "veth3b0b27d" status: Command '['/usr/bin/networkctl', 'status', '--no-pager', '--no-legend', '--', 'veth3b0b27d']' returned non-zero exit status 1.
Sep  3 12:54:19 ip-172-31-42-86 networkd-dispatcher[451]: WARNING:Unknown index 83 seen, reloading interface list
Sep  3 12:54:19 ip-172-31-42-86 systemd[1]: run-docker-netns-27d876b584e7.mount: Deactivated successfully.
Sep  3 12:54:19 ip-172-31-42-86 systemd[1]: var-lib-docker-overlay2-4e6b7965242511e3a9a34f92beded9318504c82e81d1287b0f1f28489bf63f05-merged.mount: Deactivated successfully.
Sep  3 12:54:19 ip-172-31-42-86 networkd-dispatcher[451]: ERROR:Unknown interface index 83 seen even after reload
Sep  3 12:54:23 ip-172-31-42-86 systemd[1]: run-docker-runtime\x2drunc-moby-5313d8e15a100ccf0fd50dac3c0a5088b899090a01f7a395419d843d3b393d67-runc.YRaWmN.mount: Deactivated successfully.
Sep  3 12:54:54 ip-172-31-42-86 dockerd[5230]: time="2024-09-03T12:54:54.886998534Z" level=info msg="Error logging in to endpoint, trying next endpoint" error="Get \"https://registry-1.docker.io/v2/\": toomanyrequests: too many failed login attempts for username or IP address"
Sep  3 12:54:54 ip-172-31-42-86 dockerd[5230]: time="2024-09-03T12:54:54.887121502Z" level=error msg="Handler for POST /v1.47/auth returned error: Get \"https://registry-1.docker.io/v2/\": toomanyrequests: too many failed login attempts for username or IP address"
```

**Comment by jm1021** [comment]
Kasm Error logs

```text
host: 172.31.42.86
ingest_date: 202409031249
application: kasm_agent
levelname: ERROR
process: __main__.handler
message
Error Getting Image: (kasmweb/ubuntu-jammy-desktop:1.15.0) : 401 Client Error for http+docker://localhost/v1.47/auth: Unauthorized ("Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password") 
Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http+docker://localhost/v1.47/auth

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "provision.py", line 2154, in check_images
  File "provision.py", line 2203, in get_image
  File "docker/client.py", line 199, in login
  File "docker/api/daemon.py", line 152, in login
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 401 Client Error for http+docker://localhost/v1.47/auth: Unauthorized ("Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password")
```

**Comment by jm1021** [comment]
No reply required.
