### ISSUE TITLE
[Feature Request] - AutoScale to certain amount of Cores, not the same as Standby

### ISSUE THREAD

**Issue by jm1021** [kasmtech/workspaces-issues#614]
### Existing Resources

- [x] Please search the existing issues for related items
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Is your feature request related to a problem? Please describe.**
Each day I have 30 people entering a class at about 1pm.  I want enough cores waiting plus a small Standby Pool.

ie 30 instances of a specific Workspace,  this is 60 Cores or about 30 AWS Mediums.

**Describe the solution you'd like**
 I want to have 30 AWS mediums waiting and ready for Workspace Launch.  I don't need 30 more to start autoscale process when these users get their desktops started.   Perhaps 2-3 standby's.
 
My thoughts are to have autoscale configuration change in the below to support Cores as well as Standby Cores.

Cores: 40
Standby Cores: 6

![image](https://github.com/user-attachments/assets/36367521-946f-40e7-a5be-fbf6d2f3f91e)

**Describe alternatives you've considered**
I have been working with Standby and Stagging Config.   
1. Standby of 60 cores would launch an additional Docker Agent for everyone used.
2. Staging Config is not scheduled and stated it does not support user related persistent variables.  

**Additional context**
No matter how many Standby cores I have set for the first few days of School I end up with large delays for my users and the dreaded error messages.

![image](https://github.com/user-attachments/assets/37014229-74d5-4154-b6b3-9d93d4a35d86)

![image](https://github.com/user-attachments/assets/1ff54766-c53b-4398-9978-3974a1d0878f)

Logging do not help as Kasm provides messages from i-nodes that are stale. 

```text
host: 172.31.42.43
ingest_date: 202408301300
application: kasm_manager
levelname: ERROR
process: manager_api_server
message
Future generated an exception: An error occurred (InvalidInstanceID.NotFound) when calling the TerminateInstances operation: The instance ID 'i-09b09199a9c40b435' does not exist
Traceback (most recent call last):
  File "manager_api_server.py", line 797, in do_guardian
  File "concurrent/futures/_base.py", line 437, in result
  File "concurrent/futures/_base.py", line 389, in __get_result
  File "concurrent/futures/thread.py", line 57, in run
  File "utils.py", line 1323, in provider_manager_thread_pool_wrapper
  File "provider_manager.py", line 1879, in delete_host_by_id
  File "utils.py", line 519, in wrapper_function
  File "provider_manager.py", line 1914, in delete_host
  File "providers/aws_provider.py", line 309, in destroy
  File "boto3/resources/factory.py", line 580, in do_action
  File "boto3/resources/action.py", line 88, in __call__
  File "botocore/client.py", line 530, in _api_call
  File "botocore/client.py", line 964, in _make_api_call
botocore.exceptions.ClientError: An error occurred (InvalidInstanceID.NotFound) when calling the TerminateInstances operation: The instance ID 'i-09b09199a9c40b435' does not exist
```

```text
host: 172.31.42.43
ingest_date: 202408301304
application: kasm_manager
levelname: ERROR
process: manager_api_server
message
Server f56892b0-9e52-4a36-8ec4-b385cc133947 is not present in provider aws with autoscaling config off-hours, marking for deletion
```

**Comment by j-travis** [comment]
You should be able to accomplish this with existing features.

- In your pool create one autoscale config that is specifically for the 24/7 standby instances
- Create a second autoscale config in that same pool  that is geared around the class time.  Set the standby cores to high water mark of the class. In the VM Config for that autoscale config set the max instances such that it will only ever provision the number of instances that correspond with that high watermark of users.  Set a schedule on that autoscale config to start shortly before the class starts

- https://kasmweb.com/docs/latest/guide/compute/pools.html#autoscale-scheduling

**Comment by jm1021** [comment]
Those numbers are exactly what I have been doing. The machines are all there but only a view are accepting Workspace when I look, eventually they all get in.

![image](https://github.com/user-attachments/assets/43ed6e01-285a-4798-b1f1-d5e80238cf98)

![image](https://github.com/user-attachments/assets/5fa76802-9a5d-4b9d-821e-28728c44d9d2)

**Comment by j-travis** [comment]
You'll need to triage the debug logs to see why they arent getting in. Watch the logs on the kasm_api and kasm_agent containers when they are making requests but getting denied. 

Remember that the agents will still need to download any workspace docker images you have defined (unless you bake them into the AMI). So its possible the agents are all online but they havent had enough time to download the images that are being requested. There should be logs saying that the image isnt available etc

**Comment by jm1021** [comment]
Ubuntu is being installed as a Kasm Workspace.   Do I watch those logs on kasm_web or the agent, this location /opt/kasm/current/log

2024-08-30 15:25:32,947 [DEBUG] client_api_server: Requesting Hello for Server(4a858665-99d0-4372-aa28-d5324a9f9b5f) via URL: (https://172.31.47.93:443/agent/api/v1/create_container/)
2024-08-30 15:25:33,828 [ERROR] client_api_server: Error during Create request for Server(4a858665-99d0-4372-aa28-d5324a9f9b5f) : (Exception creating Kasm: Traceback (most recent call last):
  File "__init__.py", line 573, in post
  File "provision.py", line 1939, in provision
  File "provision.py", line 2136, in generate_nginx_config
Exception: Nginx failed to reload after generating config for container (6c10bfb83348911998d1287f4b0d4c36f93f175578eedc945d84627ac3c97714)
)
2024-08-30 15:25:33,829 [DEBUG] client_api_server: Function (provider_manager.create_kasm_from_slot) executed in (0.9036321640014648) seconds
2024-08-30 15:25:33,830 [DEBUG] client_api_server: Function (provider_manager.get_container) executed in (2.5186822414398193) seconds
2024-08-30 15:25:33,831 [ERROR] client_api_server: An Unexpected Error occurred creating the Kasm. Please contact an Administrator : Error during Create request for Server(4a858665-99d0-4372-aa28-d5324a9f9b5f) : (Exception creating Kasm: Traceback (most recent call last):
  File "__init__.py", line 573, in post
  File "provision.py", line 1939, in provision
  File "provision.py", line 2136, in generate_nginx_config
Exception: Nginx failed to reload after generating config for container (6c10bfb83348911998d1287f4b0d4c36f93f175578eedc945d84627ac3c97714)
)

**Comment by jm1021** [comment]
API logs are in massive recycle.

```text
2024-08-30 15:37:50,108 [WARNING] client_api_server: Server(326c0e1f-8ddb-4162-ab91-2712f6692e3a) is not alive : <urlopen error [Errno 111] Connection refused>
2024-08-30 15:37:50,109 [DEBUG] client_api_server: Function (provider_manager.is_host_alive) executed in (0.011460304260253906) seconds
2024-08-30 15:37:50,111 [DEBUG] client_api_server: Requesting Hello for Server(4a858665-99d0-4372-aa28-d5324a9f9b5f) via URL: (https://172.31.47.93:443/agent/api/v1/hello/)
2024-08-30 15:37:50,126 [DEBUG] client_api_server: Server(4a858665-99d0-4372-aa28-d5324a9f9b5f) is alive
2024-08-30 15:37:50,127 [DEBUG] client_api_server: Function (provider_manager.is_host_alive) executed in (0.017375707626342773) seconds
2024-08-30 15:37:50,131 [DEBUG] client_api_server: Found existing server capacity: (4a858665-99d0-4372-aa28-d5324a9f9b5f).
2024-08-30 15:37:50,132 [DEBUG] client_api_server: Server (4a858665-99d0-4372-aa28-d5324a9f9b5f) has the requested image (nighthawkcoders/pusd-student-ubuntu:1.14.0-rolling) 
2024-08-30 15:37:50,134 [DEBUG] client_api_server: Requesting Hello for Server(4a858665-99d0-4372-aa28-d5324a9f9b5f) via URL: (https://172.31.47.93:443/agent/api/v1/hello/)
2024-08-30 15:37:50,150 [DEBUG] client_api_server: Server(4a858665-99d0-4372-aa28-d5324a9f9b5f) is alive
2024-08-30 15:37:50,154 [DEBUG] client_api_server: Function (provider_manager.is_host_alive) executed in (0.02030801773071289) seconds
2024-08-30 15:37:50,155 [INFO] client_api_server: Creating Kasm on Server: (4a858665-99d0-4372-aa28-d5324a9f9b5f)
2024-08-30 15:37:50,158 [DEBUG] client_api_server: Requesting Hello for Server(4a858665-99d0-4372-aa28-d5324a9f9b5f) via URL: (https://172.31.47.93:443/agent/api/v1/create_container/)
2024-08-30 15:37:51,172 [ERROR] client_api_server: Error during Create request for Server(4a858665-99d0-4372-aa28-d5324a9f9b5f) : (Exception creating Kasm: Traceback (most recent call last):
  File "__init__.py", line 573, in post
  File "provision.py", line 1939, in provision
  File "provision.py", line 2136, in generate_nginx_config
Exception: Nginx failed to reload after generating config for container (168117a8638b537b99e95c81052e5fcf1fcf3bb0ecd0ceb659e77a4cf922dcaa)
)
2024-08-30 15:37:51,173 [DEBUG] client_api_server: Function (provider_manager.create_kasm_from_slot) executed in (1.041276454925537) seconds
2024-08-30 15:37:51,175 [DEBUG] client_api_server: Function (provider_manager.get_container) executed in (2.269548177719116) seconds
2024-08-30 15:37:51,176 [ERROR] client_api_server: An Unexpected Error occurred creating the Kasm. Please contact an Administrator : Error during Create request for Server(4a858665-99d0-4372-aa28-d5324a9f9b5f) : (Exception creating Kasm: Traceback (most recent call last):
  File "__init__.py", line 573, in post
  File "provision.py", line 1939, in provision
  File "provision.py", line 2136, in generate_nginx_config
Exception: Nginx failed to reload after generating config for container (168117a8638b537b99e95c81052e5fcf1fcf3bb0ecd0ceb659e77a4cf922dcaa)
)
2024-08-30 15:37:51,177 [DEBUG] client_api_server: Function (client_api.request_kasm) executed in (2.32629656791687) seconds
2024-08-30 15:37:51,180 [INFO] cherrypy.access.134107231342208: 172.18.0.5 - - [30/Aug/2024:15:37:51] "POST /api/request_kasm HTTP/1.1" 200 100 "https://kasm.nighthawkcodingsociety.com/" "Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
2024-08-30 15:38:06,894 [DEBUG] client_api_server: Unauthenticated user made authorized API call to (healthcheck) from IP address (172.31.38.21, 172.18.0.1).
2024-08-30 15:38:06,899 [INFO] cherrypy.access.134107231342208: 172.18.0.5 - - [30/Aug/2024:15:38:06] "GET /api/__healthcheck HTTP/1.1" 200 12 "" "axios/1.6.7"
2024-08-30 15:38:06,920 [INFO] cherrypy.access.134107231342208: 172.18.0.5 - - [30/Aug/2024:15:38:06] "POST /api/guac_get_managers HTTP/1.1" 200 17 "" "axios/1.6.7"
2024-08-30 15:38:15,599 [DEBUG] client_api_server: Unauthenticated user made authorized API call to (healthcheck) from IP address (127.0.0.1).
2024-08-30 15:38:15,604 [INFO] cherrypy.access.134107231342208: 127.0.0.1 - - [30/Aug/2024:15:38:15] "GET /api/__healthcheck HTTP/1.1" 200 12 "" "curl/7.68.0"

```

**Comment by jm1021** [comment]
The nginx seems like it is your internal nginx, I made no config changes to anything other than schedule since yesterday when things were working.   It seem like servers lost their brain.  Do you recommend some sort of restart?

**Comment by jm1021** [comment]
I believe the nginx cert is coincidental to this feature request.   It seems the Kasm system healed itself in the afternoon when nobody was available to work on it.  

Observe 13 hour gap in service.

![image](https://github.com/user-attachments/assets/0fa7b516-47d1-440d-80f4-45347ec5bab1)
