### ISSUE TITLE
[Feature Request] - Kasm Workspace Killing Messages have no Published Solutions

### ISSUE THREAD

**Issue by jm1021** [kasmtech/workspaces-issues#617]
### Existing Resources

- [x] Please search the existing issues for related items
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Is your feature request related to a problem? Please describe.**
I am a new Multi-Server paying customer, but as educator discount have no human support.  I am looking for a more effective way to triage errors.  I have a couple of examples below.

We need some sort of Dashboard for common error messages, related to common actions when resources won't be provided.  Particularly if we are having errors that have been identified.

I have tried reboot kasm servers.   Deleting agent with failing reference.  But often I am shooting in the dark.  Once I have errors in one area, then I am not effective in triage of the next.

**Describe the solution you'd like**
Better or more description messages, gpt need it as well.

**Describe alternatives you've considered**
Error messages as given require drastic reaction, throw out baby and bathwater.  Because they don't manifest themself until you are downstream.

Note.  I spent 14 hours reconfiguring Kasm, autoscale/zones and Building new images (using Kasm Ubuntu).   It works my autoscale session  and then it wi fail on the next  autoscale.   It ends up not even associated with autoscale.

This week I am using Kasm Ubuntu Workspace with default AutoScale only and it worked great for me all evening.  I went into standby 0 cores and it gave me the round spinner when launching and started giving  Dashboard Login: incorrect username or password.  Then it went to red message of death.  This was long after I started to see messages that were way upstream.

**Additional context**
Here is an idea for this scenario...

1. Directions on where to see if Docker Username and Docker Password fields are correctly set, on the Workspace.
2. Provided dialog for credentials check, or how you get credentials.
3. Actions for what to do if credentials are incorrect.
4. After updating, how to test the Connection.
5. [Reference](https://www.kasmweb.com/docs/latest/guide/workspaces.html)

Here is error from Docker Agents in Dashboard Login

host: 172.31.35.60
ingest_date: 202409032037
application: kasm_agent
levelname: ERROR
process: __main__.handler
message
Error Getting Image: (kasmweb/ubuntu-jammy-desktop:1.15.0) : 401 Client Error for http+docker://localhost/v1.47/auth: Unauthorized ("Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password") 
Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http+docker://localhost/v1.47/auth

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "provision.py", line 2154, in check_images
  File "provision.py", line 2203, in get_image
  File "docker/client.py", line 199, in login
  File "docker/api/daemon.py", line 152, in login
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 401 Client Error for http+docker://localhost/v1.47/auth: Unauthorized ("Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password")

---
Never ending wait scenario
1. Directions on what to do if you get the below Nginx errors
2. Actions for how to avoid nginx errors.
3. Abandon session, close and retry
4. Don't set standby on autoscale to 0 cores

![image](https://github.com/user-attachments/assets/8ff7e850-ca8e-4640-b34c-1b0d16841a70)

host: 172.31.40.182
ingest_date: 202409040022
application: kasm_agent
levelname: ERROR
process: __main__.handler
message
Error after container creation Traceback (most recent call last):
  File "provision.py", line 1939, in provision
  File "provision.py", line 2136, in generate_nginx_config
Exception: Nginx failed to reload after generating config for container (b02131addc9f42a2ea2660bcb3f2180d9a302f9533439b0ed895ef5aeaf87f6c)
Traceback (most recent call last):
  File "provision.py", line 1939, in provision
  File "provision.py", line 2136, in generate_nginx_config
Exception: Nginx failed to reload after generating config for container (b02131addc9f42a2ea2660bcb3f2180d9a302f9533439b0ed895ef5aeaf87f6c)

host: 172.31.40.182
ingest_date: 202409040027
application: kasm_agent
levelname: ERROR
process: __main__.handler
message
Nginx reload failed (2024/09/04 00:27:55 [emerg] 474#474: cannot load certificate "/etc/ssl/certs/kasm_nginx.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/etc/ssl/certs/kasm_nginx.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0480006C:PEM routines::no start line:Expecting: TRUSTED CERTIFICATE)
)

---
This error looks nasty.  But no idea if something is just wrong in you Python.  It happens when you close/delete a workspace.

host: 172.31.42.43
ingest_date: 202409040234
application: kasm_api
levelname: ERROR
kasm_user_name: jm1021
process: root
client_ip: 172.88.77.123
user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
message
Unhandled exception occurred
Traceback (most recent call last):
  File "cherrypy/_cprequest.py", line 628, in respond
  File "cherrypy/_cprequest.py", line 687, in _do_respond
  File "cherrypy/lib/encoding.py", line 219, in __call__
  File "cherrypy/lib/jsontools.py", line 59, in json_handler
  File "cherrypy/_cpdispatch.py", line 54, in __call__
  File "utils.py", line 321, in new_func
  File "client_api.py", line 3600, in keepalive
  File "client_api.py", line 3662, in _keepalive
TypeError: 'UUID' object is not subscriptable

**Comment by jm1021** [comment]
No reply required.
