### ISSUE TITLE
[Bug] - An Unexpected Error occurred 

### ISSUE THREAD

**Issue by suporte-gavea** [kasmtech/workspaces-issues#655]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
When we attempt to create a new session, we receive the following error: "An Unexpected Error occurred creating the Kasm. Please contact an Administrator (Myself)." If we keep trying, we eventually manage to connect, but the error persists and occurs frequently.

**Error Log**
An Unexpected Error occurred creating the Kasm. Please contact an Administrator : Error during Create request for Server(7ddd9564-9a77-4c52-94a0-b0040ab093fa) : (Exception creating Kasm: Traceback (most recent call last): File "docker/api/client.py", line 268, in _raise_for_status File "requests/models.py", line 1021, in raise_for_status requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.47/containers/5fcba0584f136220cc80f582c2922490f1f44251c74fda3c245ac1a40f4f8b88/start During handling of the above exception, another exception occurred: Traceback (most recent call last): File "__init__.py", line 573, in post File "provision.py", line 1871, in provision File "provision.py", line 1863, in provision File "docker/models/containers.py", line 818, in run File "docker/models/containers.py", line 404, in start File "docker/utils/decorators.py", line 19, in wrapped File "docker/api/container.py", line 1111, in start File "docker/api/client.py", line 270, in _raise_for_status File "docker/errors.py", line 31, in create_api_error_from_http_exception docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.47/containers/5fcba0584f136220cc80f582c2922490f1f44251c74fda3c245ac1a40f4f8b88/start: Internal Server Error ("error gathering device information while adding custom device "/dev/video26": no such file or directory") )`

**Screenshots**
![Uploading Kasm Error 2.png…]()

**Workspaces Version**
1.15.0.577587

**Workspaces Installation Method**
Multi-Server (Docker).

**Client Browser (please complete the following information):**
 - OS: Windows 11 24h2
 - Browser: Google Chrome
 - Version: 131.0.6778.85

**Workspace Server Information (please provide the output of the following commands):**
**uname -a**

```
Linux rwprd01 5.15.0-125-generic #135-Ubuntu SMP Fri Sep 27 13:53:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**cat /etc/os-release**

```
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
```

**sudo docker info**

```
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.5.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 17
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 57f17b0a6295a39009d861b89e3b3b87b005ca27
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-125-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.82GiB
 Name: rwprd01
 ID: 51715514-cadf-4cd8-aa19-ee7030e659fd
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**sudo docker ps | grep kasm**

```
3fbaaf04a70f   kasmweb/nginx:1.25.3       "/docker-entrypoint.…"   4 weeks ago    Up 6 days             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
fece168874e4   kasmweb/agent:1.15.0       "/bin/sh -c '/usr/bi…"   4 weeks ago    Up 6 days (healthy)   4444/tcp                                        kasm_agent
f8812cad59f4   kasmweb/kasm-guac:1.15.0   "/dockerentrypoint.sh"   4 weeks ago    Up 6 days (healthy)                                                   kasm_guac
aa55c2c4e29d   kasmweb/manager:1.15.0     "/bin/sh -c '/usr/bi…"   4 weeks ago    Up 6 days (healthy)   8181/tcp                                        kasm_manager
fe7df5f2312b   kasmweb/share:1.15.0       "/bin/sh -c '/usr/bi…"   4 weeks ago    Up 6 days (healthy)   8182/tcp                                        kasm_share
c4ff28c80244   kasmweb/api:1.15.0         "/bin/sh -c '/usr/bi…"   2 months ago   Up 6 days (healthy)   8080/tcp                                        kasm_api
0fdab3efbdb0   redis:5-alpine             "docker-entrypoint.s…"   2 months ago   Up 6 days             6379/tcp                                        kasm_redis
c150242f8586   postgres:12-alpine         "docker-entrypoint.s…"   2 months ago   Up 6 days (healthy)   5432/tcp                                        kasm_db

```

**Additional context**
We’ve been experiencing this issue with our Kasm server since updating the Ubuntu Linux Server. We’re not sure if the update is related to the problem or not.

**Comment by j-travis** [comment]
It looks like there is a problem with the webcam passthrough virtual devices.
As a workaround, If you don't need webcam passthrough, you can update the group setting `allow_kasm_webcam` to false. This should prevent the system from trying to use them.

The kernel module needed may not be loaded. This KB may help you get situated by re-installing and configuring it:
https://kasmweb.atlassian.net/servicedesk/customer/portal/3/article/688219

**Comment by suporte-gavea** [comment]
It really worked! I applied the workaround and the issue stopped appearing. I will try the procedure of reinstalling the driver later. For now, that's it.
Thank you very much.
