### ISSUE TITLE
cifs network share doesn't work with persistent profiles

### ISSUE THREAD

**Issue by Ian-Kasmweb** [kasmtech/workspaces-issues#70]
**[Original report](https://bitbucket.org/kasmtech/kasm_release/issue/70) by reesevader NA (Bitbucket: [reesevader](https://bitbucket.org/reesevader), ).**

----------------------------------------

I was testing SMB \(CIFS\) by mounting the persistent folder and having \(for example\) teams use /mnt/kasm/persistent-profiles/teams/\{user\}/ and I get errors when launching. Any ideas?

‌

‌

```
Error during Create request for Server(16319139-2f17-4d25-8c47-4d2ce11ac136) : (Exception creating Kasm: Traceback (most recent call last): File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/docker-5.0.0-py3.6.egg/docker/api/client.py", line 268, in _raise_for_status File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/requests-2.25.1-py3.6.egg/requests/models.py", line 943, in raise_for_status requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/exec/c0cefd2f4475672b898fb55e6b3bf823afa1db342dc7bb604b79f77e3da334e8/start During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/builds/kasm-technologies/internal/kasm_backend/provision_agent/ProvisionAgent/__init__.py", line 312, in post File "/builds/kasm-technologies/internal/kasm_backend/provision_agent/ProvisionAgent/provision.py", line 473, in provision File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/docker-5.0.0-py3.6.egg/docker/models/containers.py", line 200, in exec_run File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/docker-5.0.0-py3.6.egg/docker/utils/decorators.py", line 19, in wrapped File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/docker-5.0.0-py3.6.egg/docker/api/exec_api.py", line 166, in exec_start File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/docker-5.0.0-py3.6.egg/docker/api/client.py", line 274, in _result File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/docker-5.0.0-py3.6.egg/docker/api/client.py", line 270, in _raise_for_status File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/docker-5.0.0-py3.6.egg/docker/errors.py", line 31, in create_api_error_from_http_exception docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/exec/c0cefd2f4475672b898fb55e6b3bf823afa1db342dc7bb604b79f77e3da334e8/start: Internal Server Error ("OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: process_linux.go:130: executing setns process caused: exit status 1: unknown") )
```

‌

```

Error during Create request for Server(16319139-2f17-4d25-8c47-4d2ce11ac136) : (Exception creating Kasm: Traceback (most recent call last): File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/docker-5.0.0-py3.6.egg/docker/api/client.py", line 268, in _raise_for_status File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/requests-2.25.1-py3.6.egg/requests/models.py", line 943, in raise_for_status requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.41/containers/f9e7a939effed829b0aa85e2b96d005d1756fb976571e6307e43ebe74b2ca784/exec During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/builds/kasm-technologies/internal/kasm_backend/provision_agent/ProvisionAgent/__init__.py", line 312, in post File "/builds/kasm-technologies/internal/kasm_backend/provision_agent/ProvisionAgent/provision.py", line 473, in provision File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/docker-5.0.0-py3.6.egg/docker/models/containers.py", line 196, in exec_run File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/docker-5.0.0-py3.6.egg/docker/utils/decorators.py", line 19, in wrapped File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/docker-5.0.0-py3.6.egg/docker/api/exec_api.py", line 80, in exec_create File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/docker-5.0.0-py3.6.egg/docker/api/client.py", line 274, in _result File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/docker-5.0.0-py3.6.egg/docker/api/client.py", line 270, in _raise_for_status File "/builds/kasm-technologies/internal/kasm_backend/build/virtual_environment/lib/python3.6/site-packages/docker-5.0.0-py3.6.egg/docker/errors.py", line 31, in create_api_error_from_http_exception docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/containers/f9e7a939effed829b0aa85e2b96d005d1756fb976571e6307e43ebe74b2ca784/exec: Conflict ("Container f9e7a939effed829b0aa85e2b96d005d1756fb976571e6307e43ebe74b2ca784 is restarting, wait until the container is running") )
```

‌

**Comment by teja-kasm** [comment]
We’re currently enhancing our GitHub issue tracker to improve organization and efficiency.

As part of this process, we’re closing older issues to help keep the tracker focused on current and active topics.

If this issue is still relevant or you’re still experiencing the problem, please feel free to create a new issue.

Thank you for your understanding!
