### ISSUE TITLE
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused

### ISSUE THREAD

**Issue by shermansmith** [kasmtech/workspaces-issues#80]
This appears to be the same issue as #16 but I'm unable to resolve it.

I've attempted to install kasmweb on Ubuntu 18.04, 20.04, and CentOS 8.1 - all three OS's give me the same error (below). All three attempts were made on the same Hetzner server (not a VPS or VM). I've tried verifying the kasm_db container is appropriately listening for 5432 and netstat shows it is within the container. 

Error from install.sh:

 ```
⠿ Container kasm_db  Started   3.4s
2021-11-29 23:50:54,321 [INFO] root: Performing Database Connectivity Test
2021-11-29 23:50:54,345 [INFO] root: Initializing Postgres Database
Traceback (most recent call last):
  File "sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
  File "sqlalchemy/pool/base.py", line 363, in connect
  File "sqlalchemy/pool/base.py", line 760, in _checkout
  File "sqlalchemy/pool/base.py", line 492, in checkout
  File "sqlalchemy/pool/impl.py", line 139, in _do_get
  File "sqlalchemy/util/langhelpers.py", line 68, in __exit__
  File "sqlalchemy/util/compat.py", line 129, in reraise
  File "sqlalchemy/pool/impl.py", line 136, in _do_get
  File "sqlalchemy/pool/base.py", line 308, in _create_connection
  File "sqlalchemy/pool/base.py", line 437, in __init__
  File "sqlalchemy/pool/base.py", line 639, in __connect
  File "sqlalchemy/engine/strategies.py", line 114, in connect
  File "sqlalchemy/engine/default.py", line 453, in connect
  File "psycopg2/__init__.py", line 126, in connect
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "db" (172.18.0.2) and accepting
        TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "api_server/server.py", line 100, in <module>
  File "initialize_postgres_db.py", line 16, in __init__
  File "data/data_access_factory.py", line 12, in createSession
  File "data/access_postgres.py", line 42, in __init__
  File "sqlalchemy/dialects/postgresql/base.py", line 2557, in has_table
  File "sqlalchemy/engine/base.py", line 2165, in execute
  File "sqlalchemy/engine/base.py", line 2226, in _contextual_connect
  File "sqlalchemy/engine/base.py", line 2266, in _wrap_pool_connect
  File "sqlalchemy/engine/base.py", line 1536, in _handle_dbapi_exception_noconnection
  File "sqlalchemy/util/compat.py", line 383, in raise_from_cause
  File "sqlalchemy/util/compat.py", line 128, in reraise
  File "sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
  File "sqlalchemy/pool/base.py", line 363, in connect
  File "sqlalchemy/pool/base.py", line 760, in _checkout
  File "sqlalchemy/pool/base.py", line 492, in checkout
  File "sqlalchemy/pool/impl.py", line 139, in _do_get
  File "sqlalchemy/util/langhelpers.py", line 68, in __exit__
  File "sqlalchemy/util/compat.py", line 129, in reraise
  File "sqlalchemy/pool/impl.py", line 136, in _do_get
  File "sqlalchemy/pool/base.py", line 308, in _create_connection
  File "sqlalchemy/pool/base.py", line 437, in __init__
  File "sqlalchemy/pool/base.py", line 639, in __connect
  File "sqlalchemy/engine/strategies.py", line 114, in connect
  File "sqlalchemy/engine/default.py", line 453, in connect
  File "psycopg2/__init__.py", line 126, in connect
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
        Is the server running on host "db" (172.18.0.2) and accepting
        TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/e3q8)
[8] Failed to execute script 'server' due to unhandled exception!
```

The docker container is running and psql works within the container. /etc/services within the container show 5432 is in use for postgres and attempting to curl or connect to 5432 at the container's IP from the host provides a null response, but it doesn't fail to connect.

I'm wondering if it has something to do with the Hetzner-supplied OS images, but I'm not sure where to begin testing to figure that out.

eta:

I tried running the installer with SSL disabled for the database (the -t flag). I have the same issue. If I enter the kasm_db container and add 
`host all all 172.18.0.0/24 trust`
to pg_hba.conf and then reboot the container, I can connect to it with psql from the host itself. I tried adding the trust to the copy stored on the host in /conf/database, but it still won't let me connect after I get the failure above.

**Comment by mmcclaskey** [comment]
I don't have experience with Hetzner, however, some cloud service providers (Oracle) and managed service providers, whether VM or physical, tend to use iptables as a cheap way of implementing cloud based firewalls and that has unfortunate side effects, especially for docker which heavily uses ip tables for docker networking. The first thing I would check, is what iptables rules are listed prior to installing docker. If iptables is installed and there are rules already populated, this could be the issue.

**Comment by shermansmith** [comment]
I thought of that but just to be sure, I reinstalled 20.04 on there fresh just now and made sure UFW and Iptables were both uninstalled. Then I tried the installer again and got the same error. This one is a head scratcher.

**Comment by mmcclaskey** [comment]
Instead of uninstalling iptables, try installing docker, then clearing all
rules, restart the docker service (it will recreate the missing docker
iptables rules) then install Kasm.

OR if you still have the system running, check the output of iptables -L to
see if there are any rules other than the docker chains.

Just guessing that the managed rules were re-injected by whatever software
they have running on the system.

**Comment by shermansmith** [comment]
So this got me on the right path. I started with a fresh Ubuntu 20.04, wiped all the rules from Iptables, manually installed docker and docker compose, made sure UFW was uninstalled, and then ran the installer. Worked like a charm. Whole installation was flawless after that. Thank you so much for your help.

**Comment by luc-vocab** [comment]
I had this issue as well, and I believe it was caused by left over iptables rules from the snap version of docker on ubuntu server 22.04.
so after uninstalling a previous version of docker, make sure to do `iptables -F` and reboot. Another thing that got me confused is that `ufw status` said disabled. I'm actually a noob with firewall setup, i'm not sure how iptables and ufw interact, if at all.

Here are the key debugging tools if this happens to you:
* `docker inspect kasm_db`. This will reveal the IP address of the container running the postgresql database (should be all the way at the bottom). It should match the error message _(psycopg2.OperationalError: could not connect to server: Connection timed out        Is the server running on host "db" (172.18.0.2) and accepting        TCP/IP connections on port 5432?)_
* `docker run -it --rm --network kasm_default_network busybox sh` run a container as part of the `kasm_default_network` network. this will allow you to try to connect to the database container.
* when inside the container, `telnet 172.18.0.2 5432`. you should see something like "connection established". If it hangs forever, you should suspect a firewall issue.
