### ISSUE TITLE
Kasm install erroring on database test. 

### ISSUE THREAD

**Issue by Phippre** [kasmtech/workspaces-issues#92]
Running through the Kasm install script with no luck. It's getting to point where is tests the database and then fails with the following: 

2022-01-18 00:15:34,840 [INFO] root: Performing Database Connectivity Test
2022-01-18 00:15:34,865 [INFO] root: Initializing Postgres Database
Traceback (most recent call last):
  File "sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
  File "sqlalchemy/pool/base.py", line 363, in connect
  File "sqlalchemy/pool/base.py", line 760, in _checkout
  File "sqlalchemy/pool/base.py", line 492, in checkout
  File "sqlalchemy/pool/impl.py", line 139, in _do_get
  File "sqlalchemy/util/langhelpers.py", line 68, in __exit__
  File "sqlalchemy/util/compat.py", line 129, in reraise
  File "sqlalchemy/pool/impl.py", line 136, in _do_get
  File "sqlalchemy/pool/base.py", line 308, in _create_connection
  File "sqlalchemy/pool/base.py", line 437, in __init__
  File "sqlalchemy/pool/base.py", line 639, in __connect
  File "sqlalchemy/engine/strategies.py", line 114, in connect
  File "sqlalchemy/engine/default.py", line 453, in connect
  File "psycopg2/__init__.py", line 126, in connect
psycopg2.OperationalError: could not connect to server: No route to host
	Is the server running on host "db" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "api_server/server.py", line 100, in <module>
  File "initialize_postgres_db.py", line 16, in __init__
  File "data/data_access_factory.py", line 12, in createSession
  File "data/access_postgres.py", line 42, in __init__
  File "sqlalchemy/dialects/postgresql/base.py", line 2557, in has_table
  File "sqlalchemy/engine/base.py", line 2165, in execute
  File "sqlalchemy/engine/base.py", line 2226, in _contextual_connect
  File "sqlalchemy/engine/base.py", line 2266, in _wrap_pool_connect
  File "sqlalchemy/engine/base.py", line 1536, in _handle_dbapi_exception_noconnection
  File "sqlalchemy/util/compat.py", line 383, in raise_from_cause
  File "sqlalchemy/util/compat.py", line 128, in reraise
  File "sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
  File "sqlalchemy/pool/base.py", line 363, in connect
  File "sqlalchemy/pool/base.py", line 760, in _checkout
  File "sqlalchemy/pool/base.py", line 492, in checkout
  File "sqlalchemy/pool/impl.py", line 139, in _do_get
  File "sqlalchemy/util/langhelpers.py", line 68, in __exit__
  File "sqlalchemy/util/compat.py", line 129, in reraise
  File "sqlalchemy/pool/impl.py", line 136, in _do_get
  File "sqlalchemy/pool/base.py", line 308, in _create_connection
  File "sqlalchemy/pool/base.py", line 437, in __init__
  File "sqlalchemy/pool/base.py", line 639, in __connect
  File "sqlalchemy/engine/strategies.py", line 114, in connect
  File "sqlalchemy/engine/default.py", line 453, in connect
  File "psycopg2/__init__.py", line 126, in connect
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: No route to host
	Is the server running on host "db" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/e3q8)
[6] Failed to execute script 'server' due to unhandled exception!

**Comment by j-travis** [comment]
Hello,
Can you post the output of the following commands

```
cat /etc/os-release
df
sudo docker --version
sudo docker info | grep compose
uname -a
```

**Comment by Phippre** [comment]
> 

NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

devtmpfs              8032988       0   8032988   0% /dev
tmpfs                 8068200      16   8068184   1% /dev/shm
tmpfs                 8068200   51068   8017132   1% /run
tmpfs                 8068200       0   8068200   0% /sys/fs/cgroup
/dev/mapper/cl-root  73364480 8595452  64769028  12% /
/dev/sda1             1038336  406512    631824  40% /boot
/dev/mapper/cl-home 893638320 6278300 887360020   1% /home
tmpfs                 1613640      12   1613628   1% /run/user/42
tmpfs                 1613640      68   1613572   1% /run/user/0
overlay              73364480 8595452  64769028  12% /var/lib/docker/overlay2/32b4dc28bbebb6ac01cc7697e62b4bf120a440f938e3a6eab883b7bdbba545ab/merged

Docker version 20.10.12, build e91ed57

compose: Docker Compose (Docker Inc., v2.0.1)

Linux DESKTOP-6VGMPU9 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by j-travis** [comment]
Thank you. These all look compatible 

It looks like this was previously reported by a user with a similar setup. It was a firewall issue. Can you reveiew?

https://github.com/kasmtech/workspaces-issues/issues/16

Can you share how/where you are running this distro? e.g is a particular VPS/Cloud provider/ ISO etc

**Comment by Phippre** [comment]
They are all open on the firewall. Im currently running this on a physical server.

**Comment by j-travis** [comment]
Please review the ticket carefully, This is likely a (host) firewall issue. 
There is another similar ticket : https://github.com/kasmtech/workspaces-issues/issues/80

You can also try making sure the db container is running and see if any errors are reported

```
sudo docker ps
sudo docker logs kasm_db
```

**Comment by Phippre** [comment]
< 2022-01-18 00:28:58.891 UTC     1  00000 2022-01-18 00:28:58 UTC 61e609ca.1:>LOG:  listening on IPv4 address "0.0.0.0", port 5432
< 2022-01-18 00:28:58.891 UTC     1  00000 2022-01-18 00:28:58 UTC 61e609ca.1:>LOG:  listening on IPv6 address "::", port 5432
< 2022-01-18 00:28:58.914 UTC     1  00000 2022-01-18 00:28:58 UTC 61e609ca.1:>LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
< 2022-01-18 00:28:58.937 UTC     1  00000 2022-01-18 00:28:58 UTC 61e609ca.1:>LOG:  redirecting log output to logging collector process
< 2022-01-18 00:28:58.937 UTC     1  00000 2022-01-18 00:28:58 UTC 61e609ca.1:>HINT:  Future log output will appear in directory "/var/log/postgres".

**Comment by j-travis** [comment]
So it seems like th DB container is running fine. You can try making a TCP connection to it

**Comment by Phippre** [comment]
Also I think its worth noting that I can telnet into localhost on port 5432.

**Comment by Phippre** [comment]
What do you mean b making a tcp connection to it?

**Comment by j-travis** [comment]
And what about to the containers IP `172.18.0.2` (per the log above)
Try spinning up another container on the same docker network and see if you can telnet

```
sudo docker run -it --rm --network kasm_default_network busybox sh
```

**Comment by Phippre** [comment]
I was able to telnet into the containers IP as well.

**Comment by Phippre** [comment]
I ran the command you posted above and it looks like it built then it took me to a /# prompt

**Comment by j-travis** [comment]
Run telnet from there

**Comment by Phippre** [comment]
I got a no route to host error

**Comment by Phippre** [comment]
I am able to ping though

**Comment by j-travis** [comment]
Yea - its essentially the same as the original error.

```
psycopg2.OperationalError: could not connect to server: No route to host
Is the server running on host "db" (172.18.0.2) and accepting
TCP/IP connections on port 5432?
```

**Comment by Phippre** [comment]
Yeah essentially. Im not sure what could be blocking it. All the ports are open in the firewall and the config has been saved and reloaded.

**Comment by Phippre** [comment]
I ran a docker container inspect kasm_db. Here is the network settings in the file:

"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "d72e0d855dffb986d84b1a1e7c557846c4f2c871dfce9a23aa9ff0f6a3fa497d",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5432/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/d72e0d855dff",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "kasm_default_network": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "kasm_db",
                        "db",
                        "6f58d711848c"
                    ],
                    "NetworkID": "7076436fd0571f8502d92e14212133d646b2581e64e0977e4d3f343068d20702",
                    "EndpointID": "5c1801b344a43f69eed5e83f3a7581e323ef82e2021c576ac7947e353ef646cd",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:02",
                    "DriverOpts": null
                }
            }

**Comment by Phippre** [comment]
Not sure if the line "5432/tcp": null means anything

**Comment by j-travis** [comment]
I think I need to leave it here for now.  A quick google suggests connectivity issues between docker containers is a thing with centos and `firewall-cmd` which is essentially what #16 discusses.

**Comment by Phippre** [comment]
Lol I got it working. I just read that post over again and apparently I missed the part where he added the interface to the trusted zone. Thank you for all your help. Sorry for my terrible attention to detail.
